### ISSUE TITLE
Small issues in bashdb

### ISSUE THREAD

**Issue by cpitclaudel** [realgud/realgud#109]
Two small things in bashdb:

RealGUD can't track breakpoint deletions:

```
bashdb<23> delete 8
Removed 1 breakpoint(s).
```

And the command for quit seems wrong:

```
bashdb<24> quit!
** Undefined command "quit!". Try "help".
```

**Comment by rocky** [comment]
Commit https://sourceforge.net/p/bashdb/code/ci/a77e9c180c2013292560e2513097118c67b5c267/ will address this. I'll revise the realgud code to address this and quit!

**Comment by cpitclaudel** [comment]
Brilliant, thanks!

**Comment by rocky** [comment]
New releases for bashdb and zshdb are at https://sourceforge.net/projects/bashdb/files/?source=navbar

Who knows when they'll get propagated to distributions, but eventually it'll happen.

**Comment by cpitclaudel** [comment]
Thanks a lot! :)
