### ISSUE TITLE
realgud:tooltip-eval problem

### ISSUE THREAD

**Issue by sukeyisme** [realgud/realgud#122]
when i in evil normal state ,realgud:tooltip-eval will be invaild .it show "command-execute: realgud:tooltip-eval must be bound to an event with parameters"  any advise?

**Comment by rocky** [comment]
I can't reproduce this behavior. Here is what I did.

I install evil. Then I edit a shell program, `/etc/profile` and run the realgud's  `bashdb` on it . I notice that the short-key bindings are not in effect, because evil's binding are used. For example `M-: help-for-help key e` runs  `evil-forward-word-end` which seems like a bug because in this read-only mode I'd like realgud's shortkey bindings to take precedence over evil bindings.  

Is this what you have as well? 

But at any rate, when I select to `Debugger` in the menu and then hover over the dropdown `Evaluate string or region` I do see the proper tooltip. Do you get something different? 

At any rate, this kind of level of detail is what is needed for steps to reproduce the problem is probably needed to move this forward.

**Comment by sukeyisme** [comment]
Doesn't seem to be what you said. I use mouse-2 (middle button) in evil normal state .then show "command-execute: realgud:tooltip-eval must be bound to an event with parameters". if i select the word what i want to show it's value,show this error too.

**Comment by rocky** [comment]
What is the version on your realgud? If you are not using 
version 20160606.526, use that. 

Also, in one of the shortkey-mode source buffers gat a list of the keybinding M-x - or for you Esc : - and help-for-help bindings and paste that.

**Comment by sukeyisme** [comment]
realgud-20160604.822

**Comment by sukeyisme** [comment]
You have typed , the help character.  Type a Help option:
(Use SPC or DEL to scroll through this text.  Type q to exit the Help command.)

a PATTERN   Show commands whose name matches the PATTERN (a list of words
              or a regexp).  See also the `apropos' command.
b           Display all key bindings.
c KEYS      Display the command name run by the given key sequence.
C CODING    Describe the given coding system, or RET for current ones.
d PATTERN   Show a list of functions, variables, and other items whose
              documentation matches the PATTERN (a list of words or a regexp).
e           Go to the *Messages* buffer which logs echo-area messages.
f FUNCTION  Display documentation for the given function.
F COMMAND   Show the Emacs manual's section that describes the command.
g           Display information about the GNU project.
h           Display the HELLO file which illustrates various scripts.
i           Start the Info documentation reader: read included manuals.
I METHOD    Describe a specific input method, or RET for current.
k KEYS      Display the full documentation for the key sequence.
K KEYS      Show the Emacs manual's section for the command bound to KEYS.
l           Show last 300 input keystrokes (lossage).
L LANG-ENV  Describes a specific language environment, or RET for current.
m           Display documentation of current minor modes and current major mode,
              including their special commands.
n           Display news of recent Emacs changes.
p TOPIC     Find packages matching a given topic keyword.
P PACKAGE   Describe the given Emacs Lisp package.
r           Display the Emacs manual in Info mode.
s           Display contents of current syntax table, plus explanations.
S SYMBOL    Show the section for the given symbol in the Info manual
              for the programming language used in this buffer.
t           Start the Emacs learn-by-doing tutorial.
v VARIABLE  Display the given variable's documentation and value.
w COMMAND   Display which keystrokes invoke the given command (where-is).
.           Display any available local help at point in the echo area.

C-a         Information about Emacs.
C-c         Emacs copying permission (GNU General Public License).
C-d         Instructions for debugging GNU Emacs.
C-e         External packages and information about Emacs.
C-f         Emacs FAQ.
C-m         How to order printed Emacs manuals.
C-n         News of recent Emacs changes.
C-o         Emacs ordering and distribution information.
C-p         Info about known Emacs problems.
C-t         Emacs TODO list.
C-w         Information on absence of warranty for GNU Emacs.

**Comment by cpitclaudel** [comment]
@sukeyisme Thanks for the report. However, this is very hard to reproduce currently.

Please use `toggle-debug-on-error` to get an error trace, reproduce the error, and give us the resulting error message.

Additionally, can you try reproducing the bug without evil-mode?

**Comment by rocky** [comment]
@sukeyisme when you see that long list, try typing "b" ("Display all bindings"). And this past that output. Thanks.

**Comment by sukeyisme** [comment]
@rocky i flow your step.i find in normal state <mouse-2> binding to mouse-yank-primary. how can i rebinding to realgud:tooltip-eval

**Comment by sukeyisme** [comment]
@cpitclaudel 
Debugger entered--Lisp error: (error "realgud:tooltip-eval must be bound to an event with parameters")
  call-interactively(realgud:tooltip-eval record nil)
  command-execute(realgud:tooltip-eval record)
  helm-M-x(nil "realgud:tooltip-eval")
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
  call-interactively(realgud:cmd-eval)
  realgud:cmd-eval-dwim()
  call-interactively(realgud:cmd-eval-dwim nil nil)
  command-execute(realgud:cmd-eval-dwim)

this error appear when i select a word then M-x realgud:tootip-eval

**Comment by cpitclaudel** [comment]
Just to clarify: you're running `M-x realgud:tooltip-eval`? In that case, the answer is just to run `M-x realgud:cmd-eval-dwim`

**Comment by sukeyisme** [comment]
@cpitclaudel thanks! but sometime  if i want to use <mouse-2> in normal state,how can do that?

**Comment by cpitclaudel** [comment]
Sorry, I don't understand your question. Can you clarify?

**Comment by sukeyisme** [comment]
in evil insert state mouse-2(middle mouse button) binding to realgud:tooltip-eval ,but evil normal state does not.
