### ISSUE TITLE
Remote debugging python code with pdb

### ISSUE THREAD

**Issue by xitkov** [realgud/realgud#128]
I am running a vagrant machine, which runs my python code.

Can somebody help me in setting up realgud:pdb so that I can debug code running inside vagrant from my mac?

I tried using realgud:pdb-remote, still no success.

**Comment by rocky** [comment]
Can you run `telnet <hostname> port-number` outside of emacs on your mac to connect to your vagrant machine?

**Comment by xitkov** [comment]
Yes, I can.

**Comment by rocky** [comment]
I see a bug on the realgud side. How are you setting up the remote session: via remote-pdb, pdbx or something else? 

One quick thing to try is to change `pdb-remote-query-cmdline` to `pdb-query-cmdline` in: 
https://github.com/realgud/realgud/blob/master/realgud/debugger/pdb/pdb.el#L99

**Comment by xitkov** [comment]
I am using rpdb to set up the remote session.
Using `telnet 127.0.0.1 4444` via running realgud:pdb-remote works now.

Now breakpoints are being set with local path.
I think there should be a mapping between local path and remote path, just like
the likes of [PyCharm](https://blog.jetbrains.com/pycharm/2010/12/python-remote-debug-with-pycharm/) and [Netbeans](https://blogs.oracle.com/netbeansphp/entry/path_mapping_in_php_debugger) provide.

**Comment by jmercouris** [comment]
@rajats105 I am trying to get telnet to work using rpdb, just to be clear, you have something like:

file.py
`
import rpdb
debugger = rpdb.Rpdb(port=4000)
debugger.set_trace()

print('Hello World')
`

on your vagrant box. Then you SSH into your vagrant box and run `python file.py`, and then on your host machine you execute `telnet localhost 4000`?

How did you set up your vagrant file? What versions of stuff are you using? Thanks!

**Comment by rajats105** [comment]
@jmercouris, you need to forward port 4000 from your vagrant machine to your system.

`config.vm.network :forwarded_port, guest: 4000, host: 4000`

Alternatively, you can do it using ssh tunneling too, it will work for any remote machine.

`ssh -L 4000:127.0.0.1:4000 <vagrant_user>@<vagrant_host>`

Then from your system, do `telnet 127.0.0.1 4444`.

**Comment by jmercouris** [comment]
That is very strange, somehow it worked with the tunnelling, but the other means did not work, I cannot explain it
