### ISSUE TITLE
realgud-populate-common-fn-keys-standard is always run, even when not configured

### ISSUE THREAD

**Issue by dfeich** [realgud/realgud#129]
The `realgud-populate-common-fn-keys-standard map` function is always run, even when `realgud-populate-common-fn-keys-function` is configured as nil as described in the docu

In /realgud/common/key.el, function `realgud-populate-common-keys`:

I think that the last of the following three lines should be erased. In the default configuration it is redundant, because the `realgud-populate-common-fn-keys-function` contains `realgud-populate-common-fn-keys-standard`. If I configure nil in this variable, the standard map is still set up (overwriting most of my function key definitions in python mode) due to the function being called explicitely in the third line.

```emacs-lisp
  (if realgud-populate-common-fn-keys-function
      (funcall realgud-populate-common-fn-keys-function map))
  (realgud-populate-common-fn-keys-standard map)
```

Sorry for not providing a pull request, but since it's just a line, I decided to send it like this.

Best regards,
Derek

**Comment by rocky** [comment]
Sounds reasonable to me to remove. But I'll wait on @cpitclaudel to comment.

**Comment by cpitclaudel** [comment]
I was going to say the same :) Thanks for tracking down the issue and suggesting a fix.

I'll be happy to push this fix, but I also like to give credit, even for small things. If you want to make a pull request, I'll happily apply it.
