### ISSUE TITLE
gdb-pid-associate does not work with (new) cmdbuf-associate

### ISSUE THREAD

**Issue by jbeigel** [realgud/realgud#132]
Hi,

I found the function realgud:gdb-pid-associate which looked like a very good fit quickly start debugging a running process from inside a source file. But realgud:cmdbuf-associate has been changed, so that this function does not work any more (it used to pass params to realgud:cmdbuf-associate which doesn't take any params now).

Regards,
Johannes

**Comment by rocky** [comment]
I think cc32bab will do it. If not, reopen.
