### ISSUE TITLE
shortkeys-mode behavior

### ISSUE THREAD

**Issue by ilohmar** [realgud/realgud#138]
What is the correct way to turn on/off shortkeys-mode in src buffers?  When I press <Insert> it seems that the mode is turned off, but the keys are still bound..

Relatedly, how can I reliably customize keys of the shortkey mode map?

**Comment by rocky** [comment]
Command `realgud-short-key-mode` toggles the mode. This follows the convention most other minor modes. It is bound to the "insert" key of the keymap`realgud:shortkey-mode-map`. 

Inside shortkey mode, when I run `M-x  help-for-help mode` I see the mode listed as a minor mode. And when I toggle it by pressing the "insert" key or by running that command, I no longer see the minor mode listed. And bindings in the mode map no longer are bound. 

So in short, either I am not getting the same results as you, and/or you are not explaining details precisely, or may be misunderstanding something. 

As for customizing, you do it the same as any other minor mode. 

```
(define-key realgud:short-key-mode-map ... )
````

Lastly, am not sure github issues here are a good place for asking generic questions. http://emacs.stackexchange.com/questions/tagged/realgud feels like a better place. So if this doesn't, answer your question, and it feels like it might not, then ask over there. 

In the event that this does clear up some mystery, consider helping out others by adding information to the [wiki](https://github.com/realgud/realgud/wiki).
