### ISSUE TITLE
Naming conflicts when installed to site-lisp

### ISSUE THREAD

**Issue by dunn** [realgud/realgud#143]
This isn't the usual package setup, so feel free to tell me I'm on my own here.

I install packages [through Homebrew](https://github.com/Homebrew/homebrew-emacs) rather than with `package.el`.  They're installed into subdirectories of the global `share/emacs/site-lisp` directory rather than into `~/.emacs.d/elpa`.  As a result, `subdirs.el` adds realgud's subdirs to the load-path at the same time as the system libraries, and things like `info.el` and `js.el` can take precedence over the internal ones.

Maybe this is just an argument against using `site-lisp` for anything other than what comes with Emacs, but until `package.el` that was a relatively common practice, wasn't it?

**Comment by rocky** [comment]
I'm for making accommodations to make this work on different packaging systems and environment. Provided things aren't too wacky. But I don't see why it would be the case here.

Right now, I don't understand the problem.  I don't have an OSX box so I can't try out homebrew, but I do have a clean VM for centos7 where I could try installing this via configure into `/usr/share/emacs-site-lisp` and that worked out fine. 

Of course you need to install the prerequisite packages like `loc-changes`, `load-relative` and so on, and I think you must have done that.  I use `./configure --prefix=/usr --datadir=/usr/share/` but you will probably have to adjust the paths to `share` and I'm not sure what to use for `--prefix` if that's needed at all.

But after doing this and running `make install` the files and the subdirectories copied keeping the directory structure. And a fresh load of emacs found and loaded all of the files.

So now to your point about name conflicts like `info.el` and `js.el`.  The only way I can figure this would happen is if you _flatten_ the filesystem files and that would be an utter disaster as each debugger uses the same sets of names like `init.el`,  `core.el` `track-mode.el` and so on. 

All of those files should be loaded from the appropriate subdirectory via `load-relative`.

**Comment by dunn** [comment]
The only possibly unusual setting Homebrew uses to build Emacs is `--enable-locallisppath=#{HOMEBREW_PREFIX}/share/emacs/site-lisp`, where `HOMEBREW_PREFIX` is generally `/usr/local`.

>  The only way I can figure this would happen is if you flatten the filesystem files and that would be an utter disaster as each debugger uses the same sets of names like init.el, core.el track-mode.el and so on.

It's not flattened, but the `subdirs.el` installed by Emacs does a recursive search:
```lisp
(if (fboundp 'normal-top-level-add-subdirs-to-load-path)
    (normal-top-level-add-subdirs-to-load-path))
```
And that doesn't look like a macOS specific thing: https://github.com/emacs-mirror/emacs/blob/master/Makefile.in#L479-L487

**Comment by rocky** [comment]
Hmm.  How about  writing a program that _removes_ things in _path_ that start `realgud/`

**Comment by dunn** [comment]
That'll work for the short-term; ultimately I think this is an issue with `--enable-locallisppath`; it should be adding the given path to `'load-path` after adding the core libraries.  Hopefully that won't be too hard to fix.

**Comment by rocky** [comment]
In this talk from a long time ago](https://vimeo.com/40200534), I describe why I added load-relative and why I think a `load-path` with all of those directories in it is evil.

**Comment by npostavs** [comment]
I think you just need to add a `.nosearch` file to realgud's subdirectories.

```
normal-top-level-add-subdirs-to-load-path is a compiled Lisp function
in ‘startup.el’.

(normal-top-level-add-subdirs-to-load-path)

Recursively add all subdirectories of ‘default-directory’ to ‘load-path’.
More precisely, this uses only the subdirectories whose names
start with letters or digits; it excludes any subdirectory named ‘RCS’
or ‘CVS’, and any subdirectory that contains a file named ‘.nosearch’.
```

**Comment by rocky** [comment]
All of them or just the top-level one? 

Would you please experiment and make a pull request?  Thanks.

**Comment by npostavs** [comment]
See #144.

**Comment by dunn** [comment]
🎊
