### ISSUE TITLE
Breakpoint icon not showing on Mac

### ISSUE THREAD

**Issue by ethanluoyc** [realgud/realgud#147]
Hi,

I am using this package from a Mac to debug Python programs with pdb/ipdb. I am unable to see the breakpoint icons as indicated in the README. Furthermore, when clicking on the same line in the source file, it repeatedly sets breakpoints on the same line instead of toggling the breakpoint on/off.

I think this is a platform specific problem as I checked my configuration on Ubuntu which works normally.

![image](https://cloud.githubusercontent.com/assets/6040760/17643249/a89780e6-6196-11e6-9c89-f50f11b6bbe1.png)

Thank you!

**UPDATE**
Some tracing leads me to https://github.com/realgud/realgud/blob/master/realgud/common/buffer/source.el#L182 it looks like that `marker-buffer` returns nil for loc objects that correctly belongs to the src-buffer. `realgud-loc-marker` returns a marker with no buffer. Not sure whether this is useful but just to be included here as a reference for debugger

**Comment by cpitclaudel** [comment]
Hmm. This is rather surprising.

Can you reproduce this in emacs-Q?

**Comment by ethanluoyc** [comment]
I can reproduce with Emacs -Q. I tried Emacs -Q on both Mac and Ubuntu.
Sent from my iPhone, sorry for the brevity.




On Sun, Aug 14, 2016 at 3:55 AM +0800, "Clément Pit--Claudel" <notifications@github.com> wrote:












Hmm. This is rather surprising.



Can you reproduce this in emacs-Q?

**Comment by rocky** [comment]
It is possible this some sort of terminal interaction. So it's not the OS directly and it might not be you emacs profile directly, but indirectly these influence the type of terminal, its characteristics, and how it is reflected inside emacs. 

Something else you might want to look at is the how the output-filter functions differ.

**Comment by ethanluoyc** [comment]
@rocky I think it would be nice if someone can try to reproduce this on another Mac. Currently, I have no idea why this is failing too. I am unable to debug further from the point I mentioned earlier.

**Comment by rocky** [comment]
I'd like to break down the behavior and try to offer what is going on. (I don't know though what is _wrong_.) 

You are in the source buffer and you click on line 5. Every time you do that you should in _response_ see in the command buffer  "break /Users/ethan/dev/test.py" followed by a response from ipdb  "Breakpoint xxx at ..." . 

So the breakpont is getting set in ipdb and it is reporting that; realgud however doesn't see that message as reflecting the breakpoint was set. That's why I think this is some sort of terminal interaction thing. 

When realgud misses this, it of course doesn't update status. And you can verify that  realgud missed getting status on the breakpoint by going into the command window and hitting the Debugger Info button or running `M-x realgud:cmdbuf-info-describe`. Then look in the first section for `  - Breakpoint list   ::`.

**Comment by rocky** [comment]
@ethanluoyc I cool with waiting for someone else who has a Mac to help out. I generally don't use them myself. 

What you _can_ do however is report more facts, like checking output filter functions that are installed, comparing the list of minor modes for discrepancies and so on.

**Comment by ethanluoyc** [comment]
What do you mean by `output-filter`  functions?

I followed your advice to check `realgud:cmdbuf-info-describe`, it actually does capture the breakpoints so the section - Breakpoint list has content:

![image](https://cloud.githubusercontent.com/assets/6040760/17646613/52dc017c-6204-11e6-9058-d022f760916b.png)

**Comment by rocky** [comment]
This helps. I was wrong about the terminal stuff. The problem is that inside the breakpoint list: `#<marker in no buffer>` . Emacs uses ELisp markers objects to associate positions. 

https://github.com/realgud/realgud/blob/master/realgud/common/track.el#L214  and `realgud-track-bp-loc` is what is supposed to figure out the file name and set a mark there. 

One thing that looks odd to me is the backslashes in the filename. That is: 

> ```- Command-line args ::    ["ipdb","\/Users\/Ethan\/dev\/test.py"]```

Have any idea why the backslashes appear?

**Comment by ethanluoyc** [comment]
@rocky I have no idea about the backslashes, it does not look like there is the need to do escape here. However, this backslashes also appear on Ubuntu so I guess it should be fine.

I traced the source yesterday but I couldn't figure out how you added the markers when you first hit cmd-break. That's what prohibiting me from going further.

**Comment by rocky** [comment]
For edebug tracing, trace `realgud-track-bp-loc`.

**Comment by ethanluoyc** [comment]
@rocky At https://github.com/realgud/realgud/blob/master/realgud/common/track.el#L478, it returns `nil`, this gets passed later to `loc-or-error` to create the problematic marker

**Comment by rocky** [comment]
I don't think it returns exactly at that line: 
`(source-str (and text-group (match-string text-group text)))`

What we want to know is whether `filename` and `lineno` on line 489 are set. If not then why is it matching the regexp but not the line and file groups. See https://github.com/realgud/realgud/blob/master/realgud/debugger/ipdb/init.el#L66-L72

**Comment by ethanluoyc** [comment]
No problem，I am currently away from my laptop. Will look at this once I return!

Sent from my iPhone, sorry for the brevity.




On Sun, Aug 14, 2016 at 10:36 AM +0800, "R. Bernstein" <notifications@github.com> wrote:












I don't think it returns exactly at that line: 

(source-str (and text-group (match-string text-group text)))



What we want to know is whether filename and lineno on line 489 are set. If not then why is it matching the regexp but not the line and file groups. See https://github.com/realgud/realgud/blob/master/realgud/debugger/ipdb/init.el#L66-L72

**Comment by ethanluoyc** [comment]
Ok a few updates:

- Suspicion One: When I set ONE breakpoint on the Python file, it will append three breakpoints to `Breakpoint List::`, I am not sure if this is the expected, probably not :(

- Suspicion Two: The call into `realgud-track-bp-loc` has argument `text` equal to "break /Users/Ethan/dev/test.py:5\nBreakpoint 1 at /Users/Ethan/dev/test.py:5\nipdb>" this correctly yields `filename` to "/Users/Ethan/dev/test.py" and `lineno` to  "5". Followed by this, on line 494 it incorrectly returns a `realgud-loc` on line 494, with `#<marker in no buffer>`. Before line 509, it already has two elements in the bp-list, so line 509 really adds the marker, making the three.

I am not sure why it is working like this.. Perhaps some global states are interfering with the function?

**Comment by rocky** [comment]
Yes, there should be one breakpoint per action. But let's leave that aside for now. 

It looks like  `realgud:file-loc-from-line` is the function we want to edebug now.

**Comment by ethanluoyc** [comment]
@rocky This may sound like magic....

But after a reinstall......... Everything works proper...
Let's close the issue, it's quite embarrassing.

**Comment by rocky** [comment]
Ok.
