### ISSUE TITLE
Trepanjs not showing breakpoint arrow in fringe.

### ISSUE THREAD

**Issue by sandric** [realgud/realgud#149]
When using trepanjs debugger for nodejs program by invoking M-x `realgud:trepanjs` when setting breakpoint it is works as expected but not showing breakpoint arrow in fringe (current execution arrow is shown).

**Comment by rocky** [comment]
Branch [breakpoint-display(https://github.com/realgud/realgud/tree/breakpoint-display) may address this here and in other debuggers more often. 

@cpitclaudel please review. I'm not seeing the entire line highlighted like I think it should. I'll track down what does this via git history when I get a chance. But an independent review is always good.

**Comment by rocky** [comment]
@sandric try out what's in the breakpoint-display branch and let me know if this works better. Thanks.

**Comment by sandric** [comment]
@rocky Yes, I tried and confirm that realgud:trepanjs after setting breakpoint display it in fringe, although it displays with red rectangle instead of arrow, I understand that its for testing purposes? Also I tried to check if that branch fixes the same for realgud:byebug and seems not - there's still no fringe breakpoint when I try to set it.

**Comment by rocky** [comment]
@sandric  Thanks for testing. I'll merge this code in. 

As for byebug that's a different story. I have a pull request in from over a month ago for that. See https://github.com/deivid-rodriguez/byebug/pull/281.  If you use my fork of byebug you should see the status updated properly.
