### ISSUE TITLE
Debugging on localhost (python)

### ISSUE THREAD

**Issue by drodrigo** [realgud/realgud#152]
Hello everyone!

I'm trying to figure out how to use realgud while running an application on my localhost.

My current workflow is that I start the local server put "import pdb pdb.set_trace()" somewhere and then I start debugging. 

I would like to know if it's possible to use realgud for this kind of environment.

Thanks a lot

**Comment by rocky** [comment]
I think  https://github.com/realgud/realgud#tracking-an-existing-debugger-process covers this. If this is not clear feel free ask or expand upon

**Comment by drodrigo** [comment]
Thanks @rocky  for your answer.

Yes, you're correct I'm able to debug now, the only problem is that I have to insert "import pdb; pdb.set_trace()" to actually start the debugger and that's kind of annoying to do every time.

But that's a different story, I'm closing this issue, thanks.

**Comment by rocky** [comment]
There are Python debuggers (my favorite of course is [trepan](http://python2-trepan.readthedocs.io/en/latest/) which works well with realgud) that let you debug at the outset.  But as you say, that's a different story and can of worms.
