### ISSUE TITLE
Expected workflow for debugging python code

### ISSUE THREAD

**Issue by wandersoncferreira** [realgud/realgud#156]
Hi, I started using the Realgud last week and I am very impressed with it. I would like to ask you help to accomplish a desired workflow while debugging python code.

I need to:

1. Start a debug using pdb:
 - Now, I use M-x realgud: python -m pdb /file/path/name.py

2. Setting persistent break points
 - Still managing to do that. Using break <line_number> for now.

3. Be able to edit a file while in debug mode. 
 - I dont know if this is desired or if I could not find the option to allow me on this yet

4. [optional] Move back to last break point after hitting errors or exceptions
 - This would be amazing. I could fix that problem editing the file and not need to restart all over the debug mode.

Thank you so much for your help in advance!!
Cheers!

**Comment by jmercouris** [comment]
I don't think you can edit a file in debug mode (the file would have to be reloaded), the whole idea of PDB is that you can execute any arbitrary python by using the ! prefix. Additionally, I don't believe you can go backwards. I think it may be helpful to go through a PDB tutorial (https://pythonconquerstheuniverse.wordpress.com/2009/09/10/debugging-in-python/)

**Comment by rocky** [comment]
Issues aren't really suited for help support request. There is some user help in [the wiki](https://github.com/realgud/realgud/wiki) . And StackOverflow was created for user questions as well.

**Comment by jmercouris** [comment]
Yes and no, this is specifically a question about using Realgud in VM over vagrant. Secondly, since GitHub does not have the concept of private messages I have no way of contacting the user directly
