### ISSUE TITLE
Incorrect formatting of eval when using realgud:ipdb

### ISSUE THREAD

**Issue by nordlow** [realgud/realgud#160]
When debugging Python with `realgud:ipdb` pressing `e`  followed by `42` converts to

`eval 42`

which errors in ipdb interpreter as

```
*** SyntaxError: invalid syntax (<stdin>, line 1)
```

Instead we should default to either of

- `eval("expr")`
- `p expr`
- `pp expr`

I would prefer `pp` (pretty printing) to be default.

I've tried

```Lisp
(setf (gethash "eval" realgud:ipdb-command-hash) "pp %s")
```

but it doesn't affect the behaviour of 

```Lisp
realgud:cmd-eval-dwim
```

which still prints

```
eval 42
```

which errors in ipdb.

Have I missed something?

**Comment by rocky** [comment]
The code was setting ipb command mappings into pdb rather than ipdb. Commit bbdeb4e should address this. 

Please double check and close if this addresses.

**Comment by nordlow** [comment]
Works! Thanks!
