### ISSUE TITLE
ipdb shouldn't print source context

### ISSUE THREAD

**Issue by nordlow** [realgud/realgud#161]
Is there a way to prevent ipdb from printing it's source context at each prompt update. It's really of no use when realgud displays the source buffer in another window all the time. It just wastes space. I've done some investigations but I haven't found any description on how disable it inside the prompt. Only examples of how to configure it inside the Python source itself:

```D
import ipdb
ipdb.set_trace()
```

I asked SO [here](http://stackoverflow.com/questions/41247128/disable-source-printing-in-ipdb)

**Comment by rocky** [comment]
The way [trepan](https://pypi.python.org/pypi/trepan/0.6.5) and [trepan3k](https://pypi.python.org/pypi?name=trepan3k) handle this to via  [`set autolist`](http://python2-trepan.readthedocs.io/en/latest/commands/set/autolist.html).

**Comment by nordlow** [comment]
That doesn't work in pdb:

```
ipdb> set autolist off
*** SyntaxError: invalid syntax (<stdin>, line 1)
```

**Comment by rocky** [comment]
Yes, I know that. It's just another reason why you should be using the more superior python trepan debugger ;-)

**Comment by nordlow** [comment]
Ok, I'll try it. In what more ways is it superior to ipdb?

**Comment by rocky** [comment]
Glad you asked. See https://pypi.python.org/pypi/trepan

A disclaimer though. It like pdb is in serious need of a rewrite and I don't have the time to do it.

**Comment by rocky** [comment]
`pip install trepan3k` should now work.

**Comment by nordlow** [comment]
Shouldn't we use pip3?

**Comment by rocky** [comment]
Well, yes, if you are on ubuntu where both python2 and python3 are installed and the system pytnon3 pip is called `pip3`. 

And you will possibly need to add `sudo`  as well if you have that installed and you are not the root user and can't write to `/usr/local/bin/usr/local/lib/python3.5/dist-packages`.

**Comment by nordlow** [comment]
Just running it as

```
trepan3k 
```

fails as

```
Traceback (most recent call last):
  File "/usr/local/bin/trepan3k", line 7, in <module>
    from trepan.cli import main
  File "/usr/local/lib/python3.5/dist-packages/trepan/cli.py", line 26, in <module>
    from trepan import debugger as Mdebugger
  File "/usr/local/lib/python3.5/dist-packages/trepan/debugger.py", line 39, in <module>
    from trepan.processor import cmdproc as Mcmdproc
  File "/usr/local/lib/python3.5/dist-packages/trepan/processor/cmdproc.py", line 27, in <module>
    from trepan.lib import display as Mdisplay
  File "/usr/local/lib/python3.5/dist-packages/trepan/lib/display.py", line 22, in <module>
    from trepan.lib import stack as Mstack
  File "/usr/local/lib/python3.5/dist-packages/trepan/lib/stack.py", line 17, in <module>
    import os, re, xdis
ImportError: No module named 'xdis'
```

**Comment by rocky** [comment]
I messed up on listing the dependencies, so run `pip3 install uncompyle6 xdis` with possibly sudo if you need that. 

I've corrected this list of dependencies so with the next release of trepan3k this should not be a problem.
