### ISSUE TITLE
realgud:pdb assumes that pdb is always run on a file

### ISSUE THREAD

**Issue by TauPan** [realgud/realgud#165]
Hi!

I use the following defun to run tests with "py.test --pdb" in a gud-buffer:
```elisp
(defun elpy-test-pytest-pdb-runner (top file module test)
  (interactive (elpy-test-at-point))
  (pdb (format "py.test --pdb -x %s"
               (cond
                (test
                 (let ((test-list (split-string test "\\.")))
                   (mapconcat #'identity
                              (cons file test-list)
                              "::")))
                (module file)
                (t "")))))
```

This works, because contrary to the docstring (Run pdb on program FILE in buffer `*gud-FILE*'.) the pdb function works on any command line.

(GNU Emacs 24.3.1 (x86_64-suse-linux-gnu, GTK+ Version 3.10.9) of 2014-11-12 on cloud104)

(Hoping to get a distribution upgrade with a newer emacs soonish, in case that's the cause of the issue.)

This makes realgud:pdb fail when called without filename or module (the last case in the cond), because it assumes there's a filename, when there's nil.
(with realgud both from melpa and elpa)

```elisp
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-directory(nil)
  realgud-exec-shell("pdb" nil "py.test" nil "--pdb" "-x")
  apply(realgud-exec-shell "pdb" nil "py.test" nil ("--pdb" "-x"))
  realgud:run-process("pdb" nil ("py.test" "--pdb" "-x") realgud:pdb-minibuffer-history nil)
  realgud:run-debugger("pdb" pdb-query-cmdline pdb-parse-cmd-args realgud:pdb-minibuffer-history "py.test --pdb -x " nil)
  pdb("py.test --pdb -x ")
  elpy-test-pytest-pdb-runner("~/tmp/" nil nil nil)
  elpy-test((4))
  (let ((elpy-test-runner elpy-test-pdb-runner)) (elpy-test test-whole-project))
  elpy-test-pdb((4))
  call-interactively(elpy-test-pdb nil nil)
```

**Comment by rocky** [comment]
If I understand this correctly (and I may not), you are hoping to run emacs lisp function realgud:pdb without a filename in the same way you can run a gud pdb without a filename, taking advantage of the undocumented fact that you don't have to give a filename when you run pdb? 

I suppose you could remove the alas for pdb and thus use gud's pdb and things will work okay, no? 

reagud uses the filename to associate a somewhat unique command-buffer name; for example `M-x realgud:pdb gcd.py` will run in command-buffer `*pdb gcd.py shell*`. 

I am sure there possibly more clever ways to come up with a buffer name and, in particular when no filename is given. But I don't see this as a burning need to address this right now.

So a suggestion is to create a alternate function to `realgud:pdb` does the right thing; or suggest a patch to realgud-exec-shell for the situation where there is a nil filename.

**Comment by rocky** [comment]
On reflection, changing `realgud-exec-shell` to use something like "None" for a file name when none is given, would be okay. But it will be a while before I get to it. So again, if you are up to it, submit a merge request.

**Comment by TauPan** [comment]
Oops, you beat me to it... disregard the commit ;)
