### ISSUE TITLE
realgud interferes with elpy

### ISSUE THREAD

**Issue by TauPan** [realgud/realgud#167]
If I load realgud:

 - elpy-mode is not automatically activated for each python file any more
 - some keybindings are shadowed (Such as "C-c C-s" for elpy-rgrep-symbol... but I'm not sure if that indcates a problem of either package)

**Comment by rocky** [comment]
By what mechanism is it that causes elpy-mode to get activated for each python file? 

realgud doesn't bind C-c C-s to a command, however it does add commands off of C-c !. 

I'm not an elpy-mode user right now and so it would take me a while to reproduced. 
As before, patches are welcome.

**Comment by rocky** [comment]
Wonder if the reason elpy-mode is not automatically activated has to do with [elpy rebinding `C-c C-f` to elpy-find-file](https://elpy.readthedocs.io/en/latest/ide.html#command-elpy-find-file). 

realgud uses the Elisp find-file functions like `find-file`, `find-file-noselect` and so on.

**Comment by TauPan** [comment]
This is totally bogus. When I open a python file, if realgud and elpy are loaded, elpy-mode is activated as well as python-mode, and all keybindings are ok.

I don't know what caused this, my guess is that I loaded an old session via session.el while my .emacs was a bit broken, and then stored the session, so session.el remembered the wrong modes.

I had something like that before, but it has nothing to do with realgud. Everything works fine both with 1.4.3 and the current version from melpa.

**Comment by TauPan** [comment]
Uhm, and forgot to say: Sorry for the noise ;)
