### ISSUE TITLE
realgud:cmd-eval-dwim should behave like eval-last-sexp

### ISSUE THREAD

**Issue by nordlow** [realgud/realgud#170]
It would be superb if `realgud:cmd-eval-dwim` could mimic behaviour of `eval-last-sexp`. This is simply a matter of copying the gdb `print`-command output response to the minibuffer.

This is especially important if the user wants to operate realgud without having to allocate screen space for the gdb shell window.

**Comment by rocky** [comment]
Ok. Suggest a patch or make a merge request. Thanks.

**Comment by nordlow** [comment]
How do I get the output from the recent gdb command?

**Comment by rocky** [comment]
Output in the command filter is funnelled through the  function realgud-track-from-region inside file track.el. 

Because everything is funnelled through that this function is a bit hairy. A better way to organize that code is needed.

**Comment by nordlow** [comment]
Any ideas on this organization?

**Comment by rocky** [comment]
I was thinking that there should be a list of functions that get registered to process the region, looking for specific items, like program status (stopped, exception),  debugger state change (breakpoint add, remove), output from specific previous commands and so on.

This is the way mode hooks work for example.

**Comment by jodonnell** [comment]
Hi just to be clear about this issue, this means when you eval something it should show up in the minibuffer as well?

If so I might take a look at making this happen as I find the experience of the point jumping over to the debugger window after every command in the source window jarring.

**Comment by rocky** [comment]
If you are doing the work, then you should do it the way you feel it best. A priori I don' t have any strong feelings on this.

 I'm not going to be fussy about the user interface of a feature that many want, unless there are serious flaws.

I suppose there is a concern of code getting executed that may cause damage, but we can negotiate that somehow and it is separate from the user-interaction part.

**Comment by nordlow** [comment]
@jodonnell: yes please, I'd be happy with you doing this work!

**Comment by jodonnell** [comment]
working on it here, https://github.com/realgud/realgud/pull/194

**Comment by rocky** [comment]
@nordlow So what you can do is pull from @jodonnell 's branch and test it out. I'll hold off on merging until we here back that you've tried it.

**Comment by nordlow** [comment]
Ok, thanks.

**Comment by jodonnell** [comment]
we can probably close this now that https://github.com/realgud/realgud/pull/194 has been merged, update and try it out @nordlow
