### ISSUE TITLE
compile error in jdb.el

### ISSUE THREAD

**Issue by djstauffer** [realgud/realgud#171]
While compiling realgud/debugger/jdb/jdb.el in emacs 26, I get this error message:

In realgud:jdb:
jdb.el:98:32:Error: missing value for ‘realgud:jdb-file-remap’ at end of setq

Looking in that file it does appear that the call to 'set' is missing a value.  So what should the value be?

**Comment by djstauffer** [comment]
Here a bit of context in the code:
...
    (if cmd-buf
	(with-current-buffer cmd-buf
	  (set (make-local-variable 'realgud:jdb-file-remap))
	  )
      )
...

**Comment by rocky** [comment]
The variable is defined in [`realgud/debugger/jdb/core.el`](https://github.com/realgud/realgud/blob/master/realgud/debugger/jdb/core.el#L57) and it is required in in `jdb.el` in [line 18](https://github.com/realgud/realgud/blob/master/realgud/debugger/jdb/jdb.el#L18).

I am not aware of Emacs 26; where does that come from?  We don't have this problem on any of the other Emacs' that I've used. Assuming you do mean Emacs 26 and not 25. Perhaps you can give more explicit instructions to reproduce this.

**Comment by djstauffer** [comment]
Emacs 26 is the development version (not yet released). So if you clone https://github.com/emacs-mirror/emacs and build from the master branch it will be verison 26.

I found this error because I was installing realgud  from melpa (realgud-20170128.727) on an Emacs 26 build.  During the install process (installing using list-packages) I got that error when jdb.el was compiled.

I can also replicate the problem, of course, by calling byte-compile-file on jdb.el from within emacs.

Emacs 26, however, is *not* the cause of the problem.  I have the current release (Emacs 25.1.1) on a different machine and I get the same error installing the package from melpa there ( also realgud-20170128.727).   And of course, byte-compile-file on jdb.el produces the same error there also.

so should this call to with-current-buffer just be setting the variable like this:

  (set (make-local-variable 'realgud:jdb-file-remap) (make-hash-table :test 'equal))

.. since the compiler is complaining that the set call has no value, and that is the value that it is set to in 
https://github.com/realgud/realgud/blob/master/realgud/debugger/jdb/core.el#L57  ?

**Comment by rocky** [comment]
> so should this call to with-current-buffer just be setting the variable like this: ...

Yes, I think so and that has now been done in  f73b9371f23442808205b6d1060e7daa1a669325

See if that fixes things. If so, close this issue. Thanks for reporting, investigating, and suggesting a fix.

**Comment by djstauffer** [comment]
Yes, it compiles without error now.  I'll go ahead and close the issue.
