### ISSUE TITLE
ANSI Escape sequences printed verbatim with realgud:ipdb

### ISSUE THREAD

**Issue by stnbu** [realgud/realgud#174]
I'm quite new to emacs so please forgive any stupid...

I have the following in my ~/.emacs

```
(add-hook 'shell-mode-hook 'ansi-color-for-comint-mode-on)
(add-to-list 'comint-output-filter-functions 'ansi-color-process-output)
```

This _does_ address a similar problem (re ANSI color sequences) with elpy+ipython.

But when I 

```
M-x load-library [RET] realgud [RET]
```

```
M-x realgud:ipdb [RET]
```

from within a python buffer, I get a new ipdb interpreter in another window (that appears to be working as expected). But I get the above mentioned ANSI color escape sequence problem:

```
Current directory: /foo/
Command: ipdb /foo/__init__.py
> /foo/__init__.py(1)<module>()
----> 1 import paramiko
      2 
      3 

[6n[Jipdb> [6D[6C
[6D[Jipdb> [6D
[J[6n[Jipdb> [6D[6C[6D[J[6n[Jipdb> [6D[6C
```

From my package listing buffer:

```
 realgud       20170218.740  installed
```

**Comment by eflanigan00** [comment]
Anyone know anything about this? I'm having the same problem.

**Comment by xkal36** [comment]
I came acroos this problem also. I detailed my fix here: https://emacs.stackexchange.com/questions/34854/ipdb-displaying-ansi-color-escape-sequences

**Comment by rocky** [comment]
@xkal36 I'd be grateful if you documented the workaround in off of https://github.com/realgud/realgud/wiki

Although beggars can't be chooser, my suggested would be to document the problem in general: ANSI escape codes in Emacs shells, and then under ipdb notes add a mention to that. Thanks in advance.

**Comment by rocky** [comment]
@stnbu  @eflanigan00 @xkal36 I have just created a branch that may address this by filtering out all ANSI escape codes. Try this patch and let me know if this helps:
 
```
diff --git a/realgud/common/track.el b/realgud/common/track.el
index f26a0ed..3097de0 100644
--- a/realgud/common/track.el
+++ b/realgud/common/track.el
@@ -41,6 +41,11 @@
   :type 'symbolp
   :group 'realgud)
 
+(defcustom realgud-strip-ansi? nil
+"If non-nil, set strip ANSI control characters from output text we see"
+  :type 'symbolp
+  :group 'realgud)
+
 (declare-function fn-p-to-fn?-alias                   'realgud-helper)
 (declare-function realgud-bp-add-info                 'realgud-bp)
 (declare-function realgud-bp-del-info                 'realgud-bp)
@@ -182,7 +187,8 @@ evaluating (realgud-cmdbuf-info-loc-regexp realgud-cmdbuf-info)"
 
   (interactive "r")
   (if (> from to) (psetq to from from to))
-  (let* ((text (buffer-substring-no-properties from to))
+  (let* ((raw-text (buffer-substring-no-properties from to))
+	 (text (if realgud-strip-ansi? (ansi-color-filter-apply raw-text) raw-text))
 	 (loc (realgud-track-loc text cmd-mark))
 	 ;; If we see a selected frame number, it is stored
 	 ;; in frame-num. Otherwise, nil.
```

It is also in the [strip-ansi-var branch](https://github.com/realgud/realgud/tree/strip-ansi-var) on github.

**Comment by rocky** [comment]
Issue moved to [realgud/realgud-ipdb #1](https://github.com/realgud/realgud-ipdb/issues/1) via [**ZenHub**](https://www.zenhub.com/)
