### ISSUE TITLE
Breakpoint icon not displaying in perldb

### ISSUE THREAD

**Issue by CeleritasCelery** [realgud/realgud#178]
When using `realgud:perldb` the breakpoint fringe icon is not being displayed. I know the breakpoint is being set. However when using `realgud:gdb` the breakpoint icons are working fine so it is not something fundamentally wrong with my setup. Also I tried this with `emacs -Q` and the problem persists, so this doesn't seem to be related to other packages. Are others able to reproduce this problem and what might be the problem?

**Comment by rocky** [comment]
I'm not seeing this problem, with `realgud:perldb`. So I wonder if it is a fringe problem or something deeper. 
When you run a simple program (for example there is one inside the realgud distribution in `test/gcd.pl` and step a bit and then issue `M-x realgud:cmdbuf-info-describe`, do you see locations listed like the below?

```#+STARTUP: showall
#+TITLE: Debugger info for *perldb gcd.pl shell*
** General Information (realgud-cmdbuf-info)
  - Debugger name     ::	"perldb"
  - Command-line args ::	["perl","-d","\/tmp\/gcd.pl","3","5"]
  - Starting directory ::	nil
  - Selected window should contain source? :: nil
  - Last input end    ::	632
  - Source should go into short-key mode? :: t
  - Breakpoint list   ::	 nil
  - Remap table for debugger commands ::
	{"kill":"*not-implemented*","jump":"*not-implemented*","down":"*not-implemented*","up":"*not-implemented*","shell":"*not-implemented*","frame":"*not-implemented*","until":"c %l","next":"n","step":"s","run":"R","restart":"R","quit":"q","eval":"x %s","continue":"c","clear":"B %l","break":"b %l","backtrace":"T"}
  - Backtrace buffer  ::	nil
  - In debugger?      ::	t

** Source Buffers Seen (srcbuf-list)
  - /tmp/gcd.pl

** Source Positions Stopped at (loc-hist)
  -  buffer size  :: 20
  -  position     :: 0
*** 0
  - filename      :: /tmp/gcd.pl
  - line number   :: 18
  - brkpt num     :: nil
  - column number :: 0
  - source text   :: die sprintf "Need two integer arguments, got %d", scalar(@ARGV) unless 
  - source marker :: #<marker at 294 in /tmp/gcd.pl>
  - cmdbuf marker :: #<marker at 345 in *perldb gcd.pl shell*>
*** 1
  - filename      :: /tmp/gcd.pl
  - line number   :: 20
  - brkpt num     :: nil
  - column number :: 0
  - source text   :: my ($a, $b) = @ARGV[0,1];
  - source marker :: #<marker at 382 in /tmp/gcd.pl>
  - cmdbuf marker :: #<marker at 397 in *perldb gcd.pl shell*>
*** 2
  - filename      :: /tmp/gcd.pl
  - line number   :: 21
  - brkpt num     :: nil
  - column number :: 0
  - source text   :: printf "The GCD of %d and %d is %d\n", $a, $b, gcd($a, $b);
  - source marker :: #<marker at 408 in /tmp/gcd.pl>
  - cmdbuf marker :: #<marker at 491 in *perldb gcd.pl shell*>
*** 3
  - filename      :: /tmp/gcd.pl
  - line number   :: 9
  - brkpt num     :: nil
  - column number :: 4
  - source text   ::     my ($a, $b) = @_;
  - source marker :: #<marker at 111 in /tmp/gcd.pl>
  - cmdbuf marker :: #<marker at 549 in *perldb gcd.pl shell*>
*** 4
  - filename      :: /tmp/gcd.pl
  - line number   :: 11
  - brkpt num     :: nil
  - column number :: 4
  - source text   ::     ($a, $b) = ($b, $a) if ($a > $b);
  - source marker :: #<marker at 152 in /tmp/gcd.pl>
  - cmdbuf marker :: #<marker at 624 in *perldb gcd.pl shell*>
*** 5
  - filename      :: /tmp/gcd.pl
  - line number   :: 13
  - brkpt num     :: nil
  - column number :: 4
  - source text   ::     return undef if $a <= 0;
  - source marker :: #<marker at 191 in /tmp/gcd.pl>
  - cmdbuf marker :: #<marker at 690 in *perldb gcd.pl shell*>
```

**Comment by CeleritasCelery** [comment]
Thank you @rocky for responding. Yes, I see the locations. I can also see the fringe arrows indicating my current and previous lines. Just not the breakpoint indicators. I also do not see my breakpoint (on line 11) in the breakpoint list. Should I?

```
#+STARTUP: showall
#+TITLE: Debugger info for *perldb gcd.pl shell*
** General Information (realgud-cmdbuf-info)
  - Debugger name     ::	"perldb"
  - Command-line args ::	["perl","-d","/nfs/site/home/tjhinckl/personal/github/realgud/test/gcd.pl","10","10"]
  - Starting directory ::	nil
  - Selected window should contain source? :: nil
  - Last input end    ::	597
  - Source should go into short-key mode? :: t
  - Breakpoint list   ::	 nil
  - Remap table for debugger commands ::
	{"kill":"*not-implemented*","jump":"*not-implemented*","down":"*not-implemented*","up":"*not-implemented*","shell":"*not-implemented*","frame":"*not-implemented*","until":"c %l","next":"n","step":"s","run":"R","restart":"R","quit":"q","eval":"x %s","continue":"c","clear":"B %l","break":"b %l","backtrace":"T"}
  - Backtrace buffer  ::	nil
  - In debugger?      ::	t

** Source Buffers Seen (srcbuf-list)
  - gcd.pl

** Source Positions Stopped at (loc-hist)
  -  buffer size  :: 20
  -  position     :: 0
*** 0
  - filename      :: /nfs/site/home/tjhinckl/personal/github/realgud/test/gcd.pl
  - line number   :: 18
  - brkpt num     :: nil
  - column number :: nil
  - source text   :: nil
  - source marker :: #<marker at 294 in gcd.pl>
  - cmdbuf marker :: #<marker at 472 in *perldb gcd.pl shell*>
*** 1
  - filename      :: /nfs/site/home/tjhinckl/personal/github/realgud/test/gcd.pl
  - line number   :: 20
  - brkpt num     :: nil
  - column number :: nil
  - source text   :: nil
  - source marker :: #<marker at 382 in gcd.pl>
  - cmdbuf marker :: #<marker at 584 in *perldb gcd.pl shell*>
*** 2
  - filename      :: /nfs/site/home/tjhinckl/personal/github/realgud/test/gcd.pl
  - line number   :: 11
  - brkpt num     :: nil
  - column number :: nil
  - source text   :: nil
  - source marker :: #<marker at 152 in gcd.pl>
  - cmdbuf marker :: #<marker at 724 in *perldb gcd.pl shell*>
```

**Comment by rocky** [comment]
Um. We don't show breakpoint _numbers_. If you know how to do that feel free to submit a pull request.

**Comment by CeleritasCelery** [comment]
Thank you for the commit. I am still a little confused then. Does the breakpoint icon work for you in `realgud:perldb` or just using `Devel:Trepan`? Does you commit fix the behavior of the breakpoint inidicator in perldb or does it just change the breakpoint face?

**Comment by rocky** [comment]
The breakpoint icon works for me in `Devel::Trepan` only. The commit just changes the breakpoint selected line and has nothing to do with perldb or any specific debugger. In some styles and terminals breakpoint selected _lines_ were not visible. There is a little redundancy here in that not only is there an indicator, but the line itself changes face. And this is particularly helpful if the indicator is missing for some other reason.

**Comment by CeleritasCelery** [comment]
Okay sounds like having no breakpoints indicators is a implementation problem. I looked into `Devel:Trepan` and it looks like a suitable replacement. Since we have a Perl debugger with working breakpoint indicators I am going to close this issue. Thanks!

**Comment by rocky** [comment]
Ok. Thanks for reporting, the feedback and then closing.

I'll look at the issues and open a more generic one if there's not already an issue filed. 

perldb isn't the only place where there is a problem. I think Python's pdb, gawk's dgawk, and probably some ruby debuggers have the problem as well. 

It is possible someday in the future we will have an alternate way to grok this information when the debugger doesn't supply any feedback on setting/removing breakpoints. So far the alternatives have been a little bit flaky given the kinds of things we can reliably do. 

As for Devel::Trepan, it has a number of  cool features of its own that then venerable perldb (or any other Perl debugger) doesn't have.

**Comment by CeleritasCelery** [comment]
I can't speak for other debuggers, but in `perl -d` it will issue a warning if a breakpoint command is illegal. So you can always assume that no message means the breakpoint properly set. This is how another emacs Perl debugger framework, [perldb-ui](https://github.com/wenbinye/emacs-pde/blob/master/lisp/perldb-ui.el), handles it.

**Comment by rocky** [comment]
realgud may eventually do that. Want to volunteer to write the code to do so?

**Comment by CeleritasCelery** [comment]
If I get some free time I may take up the challenge, though I would have to familiarize myself with the other debuggers you mentioned to make a universal implementation.
