### ISSUE TITLE
how to autoload realgud?

### ISSUE THREAD

**Issue by CeleritasCelery** [realgud/realgud#179]
I would like to create autoloads for several of the realgud launch points. I can see issues like #84 which discuss autoloads but I could not seem to understand how they are supported. if I use `(load-library "realgud")` as suggested in the README the functions are all required upfront. How do do I create autoloads for realgud? Thanks in advance.

**Comment by rocky** [comment]
See https://emacs.stackexchange.com/questions/8023/how-to-use-autoload/8027#8027 ?

**Comment by CeleritasCelery** [comment]
Thank for the quick response and information. I am not using `packages.el` however, I am using `use-package` (trying to add realgud to Spacemacs). I can see the `realgud-autoloads.el` file but I am not sure how to actually load it. calling `(load-library "realgud-autoloads")`, or `(load-file "<path>/realgud-autoloads.el")`, or `(autoload 'realgud:trepan.pl "realgud-autoloads" "realgud perl debugger" t)` doesn't work. The actual function `realgud:trepan.pl` is not on the load path.
I am aware of how `use-package` "normally" creates autoloads (with `:commands`, `:bind`, `:bind*`, `:bind-keymap`, `:bind-keymap*`, `:mode`, or `:interpreter`) but the implentation I am creating allows autoloads to be created after realgud has been defined by `use-package`. So I need to create the autoloads myself.
`

**Comment by rocky** [comment]
If I recall correctly load-relative doesn't work with spacemacs. Search on issues here for spacemacs and/or in the load-relative project. Has that been solved?

**Comment by CeleritasCelery** [comment]
I was able to find a work around using the information found [here](https://github.com/jwiegley/use-package/issues/485)
