### ISSUE TITLE
`realgud:unload-features` doesn't seem to work

### ISSUE THREAD

**Issue by roymath** [realgud/realgud#181]
I may be missing something, but I noticed that `realgud:loaded-features` returns a single string "realgud". Rewriting `realgud:loaded-features` along these lines returns a full list.. 

    (delq nil
          (mapcar (lambda (x) (and (string-match-p "^\\(realgud\\|trepan\\|nodejs\\)" (symbol-name x)) x))
                  features))

Thoughts?

**Comment by rocky** [comment]
Yes, I think you are right. However I don't see how "trepan" or "nodejs" get added in provide. I would imagine 
```
(delq nil
      (mapcar (lambda (x) (and (string-match-p "^\\(realgud:\\|realgud-\\)" (symbol-name x)) x))
              features))
```
would cover everything.

**Comment by roymath** [comment]
It looks like trepanX* and nodejs- functions are loaded by realgud as well.

    nodejs-parse-cmd-args is a compiled Lisp function in `core.el'.
    trepan2 is an alias for `realgud:trepan2' in `trepan2.el'.

Happy to help if you need me to submit a PR. I also think some ert- tests would help

**Comment by rocky** [comment]
The functions are loaded but are they  [features(https://www.gnu.org/software/emacs/manual/html_node/elisp/Named-Features.html)? 

Yes, please submit a PR.  Test's are always welcome. Currently we've been using for testing a simplified version of ert call [test-simple](https://github.com/rocky/emacs-test-simple)

**Comment by rocky** [comment]
I don't get a stack trace, and if I did, it wouldn't be a big deal. 

When I put this in a file:

```
;; Press C-x C-e at the end of the next line to run this file test non-interactively
;; (test-simple-run "emacs -batch -L %s -l %s" (file-name-directory (locate-library "test-simple.elc")) buffer-file-name)
(require 'test-simple)
(test-simple-start)
(assert-t (load-file "./junk.el")
	  "Can't load gcd.el - are you in the right directory?" )
(end-tests)
```
and run `C-x C-e` as indicated, I get: 

```
-*- mode: compilation; default-directory: "/tmp/" -*-
Compilation started at Tue Aug  1 16:12:32

emacs -batch -L /home/rocky/.emacs.d/elpa/test-simple-20170527.832/ -l /tmp/foo.el
Loading 00debian-vars...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50cmake-data.el (source)...
Loading /etc/emacs/site-start.d/50devhelp.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Loading /etc/emacs/site-start.d/50emacs-goodies-el.el (source)...
Loading /etc/emacs/site-start.d/50festival.el (source)...
Loading /etc/emacs/site-start.d/50gtk-doc-tools.el (source)...
Loading /etc/emacs/site-start.d/50pydb.el (source)...
Loading /etc/emacs/site-start.d/50systemtap-common.el (source)...
Loading /usr/share/emacs/site-lisp/systemtap-common/systemtap-init.el (source)...
Cannot open load file: no such file or directory, /tmp/junk.el

Compilation exited abnormally with code 255 at Tue Aug  1 16:12:32
```

And inside the buffer I just get a message. And when I fix the problem and run `M-x eval buffer` I get in another buffer: 

```
foo.el
.
0 failures in 1 assertion (0.00388654 seconds)
```

That said, since tests of any form are better than nothing, just write them in ert. Hard to imagine it would be that difficult in either setting. And if I find having mixed tests or ert annoying, I'll rewrite the test. Thanks.

**Comment by roymath** [comment]
Thanks for the note.. not to be a pain about it, but isn't `(assert-t` somewhat broken (i.e not showing the right message)?

    ...
    Loading /etc/emacs/site-start.d/50systemtap-common.el (source)...
    Loading /usr/share/emacs/site-lisp/systemtap-common/systemtap-init.el (source)...
    Cannot open load file: no such file or directory, /tmp/junk.el

should have read instead as:

    ...
    Loading /etc/emacs/site-start.d/50systemtap-common.el (source)...
    Loading /usr/share/emacs/site-lisp/systemtap-common/systemtap-init.el (source)...
    Can't load gcd.el - are you in the right directory?

**Comment by rocky** [comment]
For that, you should have used `assert-raises` instead of `assert-t`.

**Comment by roymath** [comment]
I've tested some changes that I'd like to contribute. Shall I open a new PR?
(fyi: When I click on new PR, the "Create Pull Request" button is grayed. Not sure why)

**Comment by rocky** [comment]
yes, that's generally how github works, and it works here too.
