### ISSUE TITLE
Installing realgud with  install-from-git.sh using defaults breaks emacs info.

### ISSUE THREAD

**Issue by dudinea** [realgud/realgud#187]
Steps to reproduce:

- use default emacs 24 installation, tested on ubuntu 16.04.02
- clone realgud git repo and run ./install-from-git.sh as root
- restart emacs
- type M-x info:
 get error: Autoloading failed to define function info

The problem is that by  default install-from-git.sh seems to install realgud into 
the /usr/local/share/emacs/site-lisp/ directory. Usually site-lisp directories and their
 subdirectories are automatically added to load path, in particular  
/usr/local/share/emacs/site-lisp/ is added to load-path before emacs system directories.
So realgud's common/buffer/info.el is loaded before emacs's info.el

Possible fix (works for me): realgud directory must contain .nosearch  file which prevents emacs from adding it load-path.

**Comment by rocky** [comment]
@dudinea please double check that this addresses the problem you've seen. I make lots of mistakes. That's why I work on debuggers.

**Comment by dudinea** [comment]
Yes, it helps: now .nosearch file is being created during installation. Thanks,  great work!
