### ISSUE TITLE
INstallation of Realgud appears to be not working. 

### ISSUE THREAD

**Issue by clozinski** [realgud/realgud#188]
Linux Debian 8

more ~/.emacs.d/init.el
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(package-initialize)

Then when I fire up emacs and type 
M-x package-refresh-contents RET 
It says 
Contacting host: melpa.org:80
 And sems to hang. 

The next command
M-x package-install RET r

Gives me the following choices.  Maybe it has not downloaded the realgud option. 

ossible completions are:
realgud-byebug                         realgud-old-debuggers
realgud-pry                            realgud-rdb2

Warm Regards
Chris

**Comment by rocky** [comment]
Offhand, this looks like a problem with your environment or melpa, not realgud. It could also be a transient problem.

Check that you can run curl or wget to the URL http://melpa.org/packages

**Comment by rocky** [comment]
Closing since this is most likely a clozinski bug, than it is a realgud bug. If someone else has a problem, we can reopen. Or us the other bug report for more information.
