### ISSUE TITLE
Can't disable realgud keybinings by customization (realgud-populate-common-fn-keys-standard)

### ISSUE THREAD

**Issue by claxclinton** [realgud/realgud#202]
Hi,
Realgud's keybinding interferes with my own, and I want to replace
realgud-populate-common-fn-keys-standard with nil in the customization
"Realgud Populate Common Fn Keys Function", but nil is not an accepted value
it seems. According to documentation, this should work "nil -- Don’t bind any keys".
Sorry for not propsing a solution, but I know next to nil about emacs lisp.

**Comment by rocky** [comment]
I think  937bea0  will address this. The value to set now is `realgud-populate-common-fn-keys-standard` not `nil`. 

Also, saving just in the session will not work. Instead, will have to save it for future sessions, and the start a new session. 

If this doesn't work feel free to reopen this issue.

**Comment by claxclinton** [comment]
It works like charm. Thanks!
