### ISSUE TITLE
Module not found for import during debug session [Python]

### ISSUE THREAD

**Issue by Nicholas-Mitchell** [realgud/realgud#211]
I am a beginner with realgud (and pdb in general), so I assume this is a simple problem.

I can run a script without any problems, but when I run `realgud;pdb` on the same script, it is unable to import modules. For example, my first line is `import numpy as np`, but it fails, saying `ImportError: 'No module named numpy'`.

I am working in virtual environments, but the mode-line in the **realgud** buffer shows that it is also in the environment I need. Is there something else I need to do?

**Comment by Nicholas-Mitchell** [comment]
Using the mouse-click2 to inspect a variable (on the next import statement: `import argparse`) I see in the debugger that realgud is indeed using the wrong python version.

The virtual env that I am in is Python3.5, but I see that the argparse module was imported from the system installation of Python2.7!

Is there a way to ensure the expected python environment is used by pdb?

**Comment by Nicholas-Mitchell** [comment]
Ok, there is a simple way, found [here](https://stackoverflow.com/questions/3734880/getting-pdb-in-emacs-to-use-python-process-from-current-virtualenv#10313090) - just start the debugger with:

``` python
python -m pdb my_script.py
```

and not using the default of just `pdb my_script.py`

**Comment by rocky** [comment]
@Nicholas-Mitchell you might consider expanding the information in the [realgud wiki section on pdb](https://github.com/realgud/realgud/wiki/pdb-notes) to help others who might encounter the same situation as you.

**Comment by anomam** [comment]
Hi @Nicholas-Mitchell ,
Did you find a way to make it work using the command ``M-x realgud:pdb`` with your virtual environment? My ``elpy-config`` tells me that everything is pointing to my virtual environment, but I can't get the debugger to use it...
Thanks for any help! @rocky any insight from you would be greatly appreciated too.

**Comment by Nicholas-Mitchell** [comment]
I use `pyvenv-workon` to select the environment (for me they are actually
Conda environments), then when in a file I run: `realgud:pdb`, which
prompts me for a command, and I have to alter the default to be: `python -
m pdb myscript.py`.
That is, I must explicitly call the pdb module using `python` plus the `-m`
flag (for module); forcing it to be run using the current environment's
python version, which then itself knows about pdb. Otherwise it totally
neglects other OS environment variables, and goes straight for the system
installation of python, e.g. in `usr/bin/`.

On 19 Mar 2018 09:42, "Marc A. Anoma" <notifications@github.com> wrote:

Hi @Nicholas-Mitchell <https://github.com/nicholas-mitchell> ,
Did you find a way to make it work using the command M-x realgud:pdb with
your virtual environment? My elpy-config tells me that everything is
pointing to my virtual environment, but I can't get the debugger to use
it...
Thanks for any help! @rocky <https://github.com/rocky> any insight from you
would be greatly appreciated too.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/realgud/realgud/issues/211#issuecomment-374137758>, or mute
the thread

**Comment by anomam** [comment]
@Nicholas-Mitchell thank you so much for the quick reply!
It worked!!! I think I was going too fast and missed that part where it actually allows you to enter ``python -m pdb ...``. Thanks again for the help!
My next goal is to be able to do the same thing using ``pytest`` and ``realgud`` at the same time (not working using this method as it doesn't let you set the breakpoints...). I will probably post another issue about it, but if you were ever successful doing this, please, let me know!
Thanks

**Comment by Nicholas-Mitchell** [comment]
You're welcome :)
I haven't used realgud with pytest, I'm afraid. I'm sure you will be able
to get it working, though, one way or another!

**Comment by Nicholas-Mitchell** [comment]
@rocky - I updated the wiki as you suggested  :smile:

**Comment by rocky** [comment]
@Nicholas-Mitchell  many thanks. I appreciate it, and I am sure many others will benefit from your assistance.  And that's how open-source code improves: it is a lot of help from lots of different people and places at different times: that thing about building or about standing on the shoulders of others, myself included.  

By the way your comment reminded me of something else that should be mentioned in this area, so check the addition I just made to that wiki entry.

**Comment by Nicholas-Mitchell** [comment]
Well said!

Thanks for the addition too; I didn't know about it!

On 22 Mar 2018 09:08, "R. Bernstein" <notifications@github.com> wrote:

@Nicholas-Mitchell <https://github.com/nicholas-mitchell> many thanks. I
appreciate it, and I am sure many others will benefit from your assistance.
And that's how open-source code improves: it is a lot of help from lots of
different people and places at different times: that thing about building
or about standing on the shoulders of others, myself included.

By the way your comment reminded me of something else that should be
mentioned in this area, so check the addition I just made to that wiki
entry.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/realgud/realgud/issues/211#issuecomment-375211664>, or mute
the thread
