### ISSUE TITLE
Pytest support

### ISSUE THREAD

**Issue by 098799** [realgud/realgud#213]
I find it convenient to debug my programs using `pytest -s` in the root of each project. Pytest automatically finds and collects all of the tests without the need to point at a particular file and it works with ipdb or pdb breakpoints. Are there any plans for implementation of pytest debugging in realgud?

**Comment by rocky** [comment]
Probably not, so feel free to implement something.

**Comment by falcowinkler** [comment]
But that should work out of the box, i am already doing it: 
` '(realgud:pdb-command-name "py.test --pdb")`

**Comment by Sasanidas** [comment]
Ping @098799

**Comment by 098799** [comment]
Sorry for not getting back to you earlier. In the "meantime" (all those years of python development) I've used pytest in the terminal, mostly with pdb++ and has gotten used to it, so I probably won't switch now.

I can confirm that the solution by @falcowinkler is fine. Closing the issue.
