### ISSUE TITLE
Check major mode with derived-mode-p

### ISSUE THREAD

**Issue by muffinmad** [realgud/realgud#216]
Hello!

Is it posible to check major mode with ```derived-mode-p``` instead of ```eq major-mode 'comint-mode``` in ```realgud:canonic-major-mode```?
This will allow to use realgud in custom major modes derived from ```comint-mode```.

Thanks.

**Comment by rocky** [comment]
Anything is possible. Would you put in a pull request so I can try it out? 

Since am not familiar with custom major modes derived from `comint-mode` it would also be useful to give a concrete example for which we can test this out on.

**Comment by muffinmad** [comment]
I will try to make RP.

There are no need to ```(or (eq major-mode 'comint-mode) (eq major-mode 'shell-mode))``` because ```shell-mode``` is actually derived from ```comint-mode```.

I'm interested in running django server in custom major mode derived from ```comint-mode```. Something like https://github.com/anachronic/projectile-django.
