### ISSUE TITLE
M-up and M-down bound on both src and cmd buffers

### ISSUE THREAD

**Issue by dzervas** [realgud/realgud#233]
I use M-up and M-down bindings for other purposes and it seems that I can't stop realgud from hijacking them. Any ideas on what I can do?

**Comment by rocky** [comment]
Unless others have suggestions, I'd say ask this on StackOverflow or something like that and see if general Emacs users have a suggestion. If the advise you get involves changing realgud, report that back here.

**Comment by articuluxe** [comment]
What have you tried?  You should be able to rebind those keys to nil in realgud keymaps, and then add your own bindings.

**Comment by dzervas** [comment]
Where are these keymaps? I was unable to find something configurable in the code

**Comment by dzervas** [comment]
I’m not using it anymore, so i’m closing this
