### ISSUE TITLE
Set breakpoint in submodule

### ISSUE THREAD

**Issue by dolorsitatem** [realgud/realgud#238]
I have a Python application split into separate modules, say `main.py` and `module.py`.  The `main.py` file is the entry point.  I would like to set a break point in `module.py` via `realgud`.  

The only way I've been able to set a breakpoint in `module.py` is by putting `import ipdb; ipdb.set_trace()` in `module.py` *before* running `realgud`.  I'm not sure how to set the breakpoint dynamically during debugging unless the debugger is currently in `module.py`.

My workflow goes like this:

```python
"""main.py"""

from module import hello

hello("Alice")
hello("Bob")
```

```python
"""module.py"""

def hello(name):
    # import ipdb; ipdb.set_trace()
    print("Hello, " + name)
```
  I run `python -m ipdb /path/to/main.py` and am taken to the debugger within `main.py`.  In the `main.py` buffer, I can use `realgud:cmd-break` to set a breakpoint.  I can't seem to do the same thing with `module.py`.

How do I set a breakpoint in `module.py` during debugging?

**Comment by dolorsitatem** [comment]
I can set a breakpoint in `module.py` using `ipdb` with `break module:5`.  The question still stands about how to do it via `realgud`.

**Comment by rocky** [comment]
I suppse go into the command buffer shell and type `break module:5`. That works, right?

**Comment by CDitzel** [comment]
it does but its cumbersome. It there some other way?

**Comment by rocky** [comment]
@CDitzel Another way is to run inside `module.py` `M-x realgud:attach-cmd-buffer` and give the command buffer that was started. Then that module is in "shortkey-mode" and entrering "b" on wherever you want to stop will work. 

I am closing this because this feels more like a question then something concrete that can be worked on.

**Comment by dolorsitatem** [comment]
Thank you for your help!  I have updated the documentation by

1. consolidating the pdb and ipdb documentation into a [single page](https://github.com/realgud/realgud/wiki/pdb-ipdb-notes) and,
2. writing up a [summary](https://github.com/realgud/realgud/wiki/pdb-ipdb-notes#setting-breakpoints-within-a-submodule) of the issue discussed here

**Comment by rocky** [comment]
@dolorsitatem Thanks! We need more people like you!
