### ISSUE TITLE
variable realgud:ipdb-command-name not working.

### ISSUE THREAD

**Issue by jayhanjaelee** [realgud/realgud#239]
I set this variable as follows
`(setq realgud:ipdb-command-name "python -m ipdb")`
But it didn't work. 

pdb command name is working. But ipdb command name is not working.
`(setq realgud:pdb-command-name "python -m pdb")`

**Comment by rocky** [comment]
The reason this doesn't work is that "python -m pdb" is utimately passed to [`start-file-process()`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Asynchronous-Processes.html) which is expecting its first arguument to be something to exec() and  command argments passed to the program to appear separately. 

Thing of this as though you did this in a shell: 

```
$ "python -m pdb" 
```

So to do what you want, use one of the [other suggestions](https://github.com/realgud/realgud/issues/96).
