### ISSUE TITLE
Wiki about unloading

### ISSUE THREAD

**Issue by gagbo** [realgud/realgud#246]
Hello,

Sorry this issue is half-question ("How do I stop debugging ?"), half-issue ("The wiki is not accurate anymore)

I've checked the wiki to try to unload features (I wanted to turn debugging off, but I'm pretty sure it wasn't the right way)

The issue is that the wiki advises to `M-x realgud-unload-features` to unload realgud, but : 

- `realgud-unload-features` looks like it was renamed `realgud:unload-features`
- `realgud:unload-features` is [not interactive](https://github.com/realgud/realgud/blob/c5d52ff4e9fdd89e94933bf2377bff3e4950f026/realgud.el#L137)

Should I `M-: (realgud:unload-features)` (so the wiki needs to be updated) **or** should I `M-x realgud:unload-features` (so a small PR should be created to make the function interactive *and* the wiki needs to be updated) ?

**Comment by rocky** [comment]
At some point I realized unloading isn't fully unloading, it is just removing the notion that a module had been provided.  If you are reloading, and there haven't been additions and deletions to functions and variables then reload works. And if there are only additions and no deletions that probably works for reload as well. 

If this answers the question close the issue and I would be grateful if you would update the information as you see fit. Thanks.

**Comment by gagbo** [comment]
I was able to search for other function names thanks to this: `realgud:cmd-kill` + `realgud:terminate | realgud:cmd-terminate` do what I meant, thanks for the clarification.
