### ISSUE TITLE
realgud:gdb does not talk to source file

### ISSUE THREAD

**Issue by Sokleidas** [realgud/realgud#251]
Hello everybody,
I’m a hobbyist (mostly Scheme) and quite new to compiled languages, so I don’t know whether I’m making a mistake I don’t know about. Unfortunately, I can’t figure out, how `realgud:gdb` talks to a source file. I’m running `realgud 1.5` from Melpa stable. Appears both on emacs 26.2 and 27.0.50.

```
~$ emacs -nw
M-x load library RET realgud RET
M-x toggle-debug-on-error
M-x realgud:gdb
Run gdb (like this): gdb example
```
yields an error:
```
Debugger entered--Lisp error: (invalid-function (ring (realgud-loc-hist-ring loc-hist)))
  (ring (realgud-loc-hist-ring loc-hist))()
  realgud-loc-hist-item-at(#s(realgud-loc-hist -1 (0 0 . [nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil])) -1)
  realgud-loc-hist-item(#s(realgud-loc-hist -1 (0 0 . [nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil])))
  realgud-get-srcbuf-from-cmdbuf(#<buffer *gdb example shell*> nil)
  realgud-get-srcbuf(#<buffer *gdb example shell*>)
  realgud-expand-format("set annotate 1" nil)
  realgud-command("set annotate 1" nil nil nil)
  realgud:gdb()
  funcall-interactively(realgud:gdb)
  call-interactively(realgud:gdb record nil)
  command-execute(realgud:gdb record)
  execute-extended-command(nil "realgud:gdb" "realgud:gdb")
  funcall-interactively(execute-extended-command nil "realgud:gdb" "realgud:gdb")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```
When entering `C-c S`, something similar:
```
Debugger entered--Lisp error: (invalid-function (ring (realgud-loc-hist-ring loc-hist)))
  (ring (realgud-loc-hist-ring loc-hist))()
  realgud-loc-hist-item-at(#s(realgud-loc-hist -1 (0 0 . [nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil])) -1)
  realgud-loc-hist-item(#s(realgud-loc-hist -1 (0 0 . [nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil])))
  realgud-get-srcbuf-from-cmdbuf(#<buffer *gdb example shell*> nil)
  realgud-get-srcbuf(#<buffer *gdb example shell*>)
  realgud-window-src-undisturb-cmd()
  funcall-interactively(realgud-window-src-undisturb-cmd)
  call-interactively(realgud-window-src-undisturb-cmd)
  popup-menu((keymap (new-file menu-item "Visit New File..." find-file :enable (menu-bar-non-minibuffer-window-p) :help "Specify a new file's name$
  menu-bar-open()
  funcall-interactively(menu-bar-open)
  call-interactively(menu-bar-open nil nil)
  command-execute(menu-bar-open)
```
Any help is appreciated! Best wishes and many thanks.

**Comment by rocky** [comment]
I just had a chance to look at this. The problem seems to be that you are using a version of Emacs that no longer supports the obsolete  [`lexical-let`](https://www.gnu.org/software/emacs/manual/html_node/cl/Obsolete-Lexical-Binding.html). What version of emacs are you using? 

Since 1.5.0 this was fixed in the "unstable' versions. I have just released 1.5.1 to address this. (Of course there have been other changes, mostly of a bug-fix nature). See https://github.com/realgud/realgud/releases/tag/1.5.1 for a little more detail.

**Comment by Sokleidas** [comment]
Great, many thanks for this fix! I’m running the development version from git (27.0.50), and the problem had also appeared on 26.2.90.

**Comment by rocky** [comment]
If this addresses the issue, please close the this. 

And thanks for reporting the problem. (Again, I am sorry I didn't have the time to look into this sooner.)

**Comment by rocky** [comment]
> the problem had also appeared on 26.2.90.

For what it is worth, 26.1 doesn't have the problem.

**Comment by Sokleidas** [comment]
> If this addresses the issue, please close the this.

Of course, sorry for overlooking this.

> And thanks for reporting the problem. (Again, I am sorry I didn't have the time to look into this sooner.)

Really no need to say sorry, many thanks again for your work.
