### ISSUE TITLE
realgud:pdb opens up in random split

### ISSUE THREAD

**Issue by CDitzel** [realgud/realgud#252]
Sometimes the source window is entirely overlaid by the pdb shell, other times they show up vertically side by side and sometimes with a horizontal split. Why is that so random and how can I define fixed rules for that?

**Comment by rocky** [comment]
People have also proposed having one of a set of fixed layouts like say you'd find in VSCode or some other IDE, e.g. a source window, a backtrace window, a command window, etc. A proto version of that was custom for debugging Ruby using the Emacs 23 or Emacs 24 api  had something like this. 

However no one seems to  know how to do something like this in Emacs whether or not it is in this package or not. I am not aware of any package that addresses how to do windowing in emacs along the lines of an IDE. 

Feel free to tackle this problem if you are so interested and have the ability. If not, it can wait until there is someone willing and able.

**Comment by CDitzel** [comment]
thank you for your reply. So i take away that it is in fact more or less random then.

**Comment by 813gan** [comment]
Fixed by 4a9c658f41aa25cf95abec246bce7134e8ce6017
