### ISSUE TITLE
why is ipdb not suggested for realgud within emacs

### ISSUE THREAD

**Issue by CDitzel** [realgud/realgud#253]
I cannot seem to get realgud:ipdb command to work within emacs. pdb works fine however.

I have ipdb installed within a virtual environment that I also enable before debugging with elpy.
But I dont get suggested ipdb as a debugger for realgud. why is that?

**Comment by rocky** [comment]
ipdb is its in it own package now: https://github.com/realgud/realgud-ipdb

We have never really had someone who was willing to maintain it past the initial changes to get it started. 

If you want to figure work on a mechanism by which to keep track of all of the external debuggers and offer those feel free to put in a PR. 

I'm closing this here though. Ipdb issues should be raised in the ipdb issue tracker https://github.com/realgud/realgud-ipdb/issues
