### ISSUE TITLE
Install issue due to trepanjs

### ISSUE THREAD

**Issue by JohnC32** [realgud/realgud#256]
The files 

     realgud/debugger/Makefile.am
     realgud/realgud/configure.ac

are missing trepanjs, e.g. the Makefile.am should have:

    SUBDIRS = \
	bashdb gdb gub kshdb \
	pdb perldb rdebug remake \
	trepan trepan2 trepan3k trepan.pl trepanjs \
	zshdb

and configure.ac should have

      realgud/debugger/trepanjs/Makefile \

Without these (require 'realgud) will fail saying it can't load trepanjs.

Also, the instructions in INSTALL.md could be improved a little. I suggest removing the reference to realgud.elc:

    * cd realgud  # where you placed the project
    * emacs
    
    * From inside emacs, evaluate:
    ```lisp
      (compile (format "EMACSLOADPATH=:%s:%s:%s:%s ./autogen.sh" (file-name-directory (locate-library "test-simple.elc")) (file-name-directory (locate-library "load-relative.elc")) (file-name-directory (locate-library "loc-changes.elc")) (default-directory)) )
      ```

The reason is that realgud.elc referenced by the current INSTALL.md lisp code doesn't exist thus locate-library on it will return nil.

**Comment by rocky** [comment]
Thanks! In the future, consider putting in a pull request - that way your changes are more likely to be applied correctly.
