### ISSUE TITLE
Unable to get realgud:gdb to track source location

### ISSUE THREAD

**Issue by JohnC32** [realgud/realgud#257]
I'm using emacs 25.1.1. on Debian 9. I've tried installing realgud from MELPA and from the current tip. In both cases, I'm unable to get it tracking source lines. Could you give me pointers on where I could look for the issue? I poked around the lisp code and the regex's look okay, though I've never used this package before (I do know a little lisp).

Repro:

    rm ~/.emacs
    install from melpa (creates ~/.emacs) 
    emacs 
    M-: 
    Eval: (require 'realgud)
    create small testgud.c, gcc -g -o testgud testgud.c
    C-c C-f testgud.c
    M-x realgud:gdb
    next, etc. don't track locations. 

![realgud](https://user-images.githubusercontent.com/18011314/69279232-eb1ec280-0bb1-11ea-8011-a6730c2e5265.gif)

**Comment by rocky** [comment]
> Could you give me pointers on where I could look for the issue? 

How about the wiki:  https://github.com/realgud/realgud/wiki/gdb-notes ? 

The wiki is  mentioned at the bottom of README.md .

**Comment by JohnC32** [comment]
I have seen the wiki and from what I can tell have things setup correctly. In the animated gif illustrates what I'm seeing - the output from gdb looks correct, e.g. the ^Z^Z lines. After I do the first "n" (next), I see output from gdb:

    (gdb) n
    ^Z^Z/mathworks/home/ciolfi/tmp/testgud.c:3:28:beg:0x5555555546bf
    (gdb) 

however the source line tracker hasn't been updated. Running M-x realgud:cmdbuf-info-describe shows the new line number (3) from gdb is not being picked up as shown below. What function processes the output from gdb, maybe if I edebug that I can see what's going wrong?

```org
#+STARTUP: showall
#+TITLE: Debugger info for *gdb testgud shell*
** General Information (realgud-cmdbuf-info)
  - Debugger name     ::	"gdb"
  - Command-line args ::	["gdb","testgud"]
  - Starting directory ::	nil
  - Selected window should contain source? :: nil
  - Last input end    ::	1101
  - Source should go into short-key mode? :: t
  - Breakpoint list   ::	 nil
  - Remap table for debugger commands ::
	{"step":"step %p","run":"run","quit":"quit","eval":"print %s","continue":"continue","clear":"clear %X:%l","break":"break %X:%l"}
  - Backtrace buffer  ::	nil
  - In debugger?      ::	t

** Source Buffers Seen (srcbuf-list)
  - testgud.c

** Source Positions Stopped at (loc-hist)
  -  buffer size  :: 20
  -  position     :: 0
*** 0
  - filename      :: /mathworks/home/ciolfi/tmp/testgud.c
  - line number   :: 2
  - brkpt num     :: nil
  - column number :: nil
  - source text   :: nil
  - source marker :: #<marker at 14 in testgud.c>
  - cmdbuf marker :: #<marker at 1080 in *gdb testgud shell*>
```

**Comment by rocky** [comment]
Reread the part about where it talks about `set annotate`. 

Yeah, I get it - like me, you make a _lot_ of mistakes - which is why you need the assistance of a debugger.

**Comment by JohnC32** [comment]
Hi 

I have:

    (gdb) show annotate
    Annotation_level is 1.

Here's another piece of data. If I create ~/.gdbinit that contains:

    define hook-stop
      echo \n
    end

tracking works! This introduces an extra new line in the output (see below),  which seems to indicate to me that something is wrong with the scanning of the output from gdb.

```
Current directory: /home/ciolfi/tmp/
Command: gdb testgud
set annotate 1
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from testgud...done.
(gdb) (gdb) b main
Breakpoint 1 at 0x6b8: file testgud.c, line 2.
(gdb) r
Starting program: /mathworks/home/ciolfi/tmp/testgud 


Breakpoint 1, main () at testgud.c:2
/mathworks/home/ciolfi/tmp/testgud.c:2:13:beg:0x5555555546b8
(gdb) n

/mathworks/home/ciolfi/tmp/testgud.c:3:28:beg:0x5555555546bf
(gdb) n

/mathworks/home/ciolfi/tmp/testgud.c:4:43:beg:0x5555555546c6
(gdb) n

/mathworks/home/ciolfi/tmp/testgud.c:5:62:beg:0x5555555546d1
(gdb) n
[Inferior 1 (process 220106) exited with code 03]

```

**Comment by rocky** [comment]
`realgud-track-comint-output-filter-hook()` is the main callback.

**Comment by JohnC32** [comment]
Thanks - I'm just getting back to looking at it and see the issue. The text parameter to realgud-track-comint-output-filter-hook() contains ANSI escape codes, e.g.

    ^[[?2004h(gdb) ^[[?2004l^[[?2004h(gdb)

(I've replaced the ESC with the two chars ^[).

This explains why adding the hook-stop to .gdbinit makes things work because the ANSI escape chars end up on another line.

It seems to me that we should update the regex comparison to strip these before doing the compare. Does this make sense? If so, I'll do it and submit a PR.

**Comment by rocky** [comment]
Thanks for asking. This kind of thing has happened before in ipdb.

I'm guessing something like https://github.com/realgud/realgud/commit/b8b587be28e15b3a053482ff9848d4259e40f13d needs to happen for gdb. (Note there already is a function _realgud:remove-ansi-schmutz()_ that does what is probably needed). 

I'm also guessing that you are the first person who has gdb producing those escapes, probably because your terminal setting is not "dumb" inside the Emacs comint shell.

**Comment by JohnC32** [comment]
Thanks - I do have a fix. Though am testing things out to ensure I hit all escape sequences.

**Comment by JohnC32** [comment]
Addressed in https://github.com/realgud/realgud/commit/2cca776d28c4d6ebef033758ef01f2af2e9b3b96
