### ISSUE TITLE
configure --prefix doesn't apply the prefix to all install locations

### ISSUE THREAD

**Issue by JohnC32** [realgud/realgud#258]
If you use ./configure --prefix=LOC doesn't prefix the lisp install location. I'm not sure if this is a doc issue or a mistake. If it's a doc issue, could you update it to indicate this can be used to configure the prefix:

./configure --prefix=INSTALL_DIR --with-lispdir=INSTALL_DIR/share/emacs/site-lisp

Also in the configure --help it would be good to indicate that --with-lispdir takes a location and --with-emacs takes a value.

**Comment by rocky** [comment]
Please submit PRs.

**Comment by JohnC32** [comment]
Will do

**Comment by JohnC32** [comment]
Updated in https://github.com/realgud/realgud/commit/2cca776d28c4d6ebef033758ef01f2af2e9b3b96
