### ISSUE TITLE
UndoDB Integration

### ISSUE THREAD

**Issue by nordlow** [realgud/realgud#261]
Is there any support for UndoDB?

https://undo.io/resources/setting-undodb-within-emacs/

**Comment by rocky** [comment]
Yes, it is in a different package though: https://github.com/realgud/realgud-undodb-gdb. 

No one has shown any interest in it, nor has anyone worked on it in a while so it may be a little out of date. 

But activity on it should be logged or tracked there, not here.

**Comment by nordlow** [comment]
Thanks!
