### ISSUE TITLE
[PDB] Allow more flexibility in initial call

### ISSUE THREAD

**Issue by sdubinsky** [realgud/realgud#262]
When I set a custom PDB call it fails unless the first word is either python or pdb.  I would like to be able to set env vars in the call, as well as to run arbitrary scripts.

For the first, I would like to be able to do `ENV=test python my_script.py`.
For the second, I would like to be able to do `./my_script.py`.

Thanks!

**Comment by rocky** [comment]
Ok. Code sometime thing up.

**Comment by sdubinsky** [comment]
Before I do, can you explain a bit why you chose to parse the commands instead of just passing a string through to the shell?

**Comment by rocky** [comment]
Sure. The front end needs to understand which parts are for  python, which are for pdb, and what the debugged script name is.
