### ISSUE TITLE
Page lists realgud:lldb as the start command but I have the latest and it isn't defined

### ISSUE THREAD

**Issue by dabrahams** [realgud/realgud#263]
https://github.com/realgud/realgud/wiki/Debuggers-Available shows that realgud-lldb is invoked by `realgud:lldb` but I installed that package and the symbol isn't defined.

**Comment by rocky** [comment]
Should be fixed now. Various conventions were forced upon us when this got into MELPA.

**Comment by rocky** [comment]
Closing duplicate issue. The other issue tracker I think is the better place for this, although in truth the wiki is in this repo.

**Comment by dabrahams** [comment]
How do I get the fixed version?  Install from realgud and/or realgud-lldb from source?

**Comment by rocky** [comment]
Look at the recent wiki change to find the correct invocation. 

Although it is great you are reporting problems, the hope in open source projects such as this one is that users can look at the code to figure out problems, and fix them, and help out. 

Helping out can take a variety of forms. For example the wiki anyone can edit so possibly the formatting in the invocation in the other columns to be more code style. 

Another thing you that might help out the project is upvote the projects you use. Personally, I use the ratings to help me decide which project to work on when there are several to choose from. The rating of realgud-lldb is extremely low which indicates to me not to spend much time on it.
