### ISSUE TITLE
Add Mobdebug

### ISSUE THREAD

**Issue by jsalzbergedu** [realgud/realgud#267]
Hello,

Ive shot off a little bit of emacs lisp and lua that adds support for mobdebug, a remote lua debugger. Here's the elisp code: https://github.com/jsalzbergedu/realgud-mobdebug .

Is there any chance it could get added to the wiki? Thank you.

**Comment by rocky** [comment]
Thanks for doing this!

Although I appreciate your asking, anyone can add to the wiki. 

And at some point you want to put this in the realgud organization with you as the owner, that's doable too.
