### ISSUE TITLE
realgud-recursive-autoloads.el missing from MELPA package

### ISSUE THREAD

**Issue by xzz53** [realgud/realgud#271]
Hi!

It looks like the latest MELPA [package](https://melpa.org/packages/realgud-20200607.416.tar) for realgud doesn't contain `realgud-recursive-autoloads.el`, thus breaking autoloads for me. Is this behavior intentional? Am i missing something?

Thanks in advance!

**Comment by rocky** [comment]
> Is this behavior intentional? 

Old sysadmin saying to ward off paranoia: never ascribe to maliciousness that which can easily be explained by oversight. 

I have no idea how `realgud-recursive-autoloads.el` works. I think @cpitclaudel created that.

The [file is in the github repo](https://github.com/realgud/realgud/blob/master/realgud-recursive-autoloads.el) so I am at a los as to why it's not in MELPA. 

If you want to track down what's up and how to fix please do so. 

Thanks in advance!

**Comment by xzz53** [comment]
I believe a trivial patch like
```diff
diff --git a/recipes/realgud b/recipes/realgud
index 1294b1c8..d1f045f1 100644
--- a/recipes/realgud
+++ b/recipes/realgud
@@ -1,7 +1,7 @@
 (realgud
  :fetcher github
  :repo "realgud/realgud"
- :files ("realgud.el" "realgud/.nosearch"
+ :files ("realgud.el" "realgud/.nosearch" "realgud-recursive-autoloads.el"
          ("realgud/common"             "realgud/common/*.el")
          ("realgud/common/buffer"      "realgud/common/buffer/*.el")
          ("realgud/debugger/bashdb"    "realgud/debugger/bashdb/*.el")

```
to the MELPA [recipe](https://github.com/melpa/melpa/blob/a81dea8fe641233c71b209233ff3c17256a2bef9/recipes/realgud) would suffice.

**Comment by rocky** [comment]
Ok. But his isn't something I changed anytime recently. Would you put in the PR to MELPA to handle? 

Thanks. 


(Technically this is not a bug in this repository but in the packaging of this. There is nothing here that needs to change. But I suppose leaving an issue here serves to alert folks).

**Comment by cpitclaudel** [comment]
Thanks @xzz53 .  Do we know what (if anything) changed on the MELPA side?

**Comment by xzz53** [comment]
> Thanks @xzz53 . Do we know what (if anything) changed on the MELPA side?

I'm not sure whether it ever worked for me. I stumbled upon this issue during attempts of making my `init.el` autoload as much things as possible.

BTW here is MELPA [PR](https://github.com/melpa/melpa/pull/6955/).

**Comment by xzz53** [comment]
https://github.com/melpa/melpa/pull/6955/ is merged now, so closing this.
