### ISSUE TITLE
realgud clobbers major modes' keymaps, and does not restore them on quit

### ISSUE THREAD

**Issue by CyberShadow** [realgud/realgud#275]
After a debugging session, I noticed that some keys stop working, even after realgud is fully exited (using `realgud:cmd-quit`).

E.g., see this with `describe-key`:

```
<M-down> runs the command realgud-track-hist-newer (found in
d-mode-map), which is an interactive compiled Lisp function in
‘realgud/common/track.el’.
```

Obviously `realgud-track-hist-newer` has no business being in `d-mode-map`.

The biggest annoyance is that this corruption is "global" - recreating the buffer (by closing and re-visiting the file) does not fix it. Only restarting Emacs helps.

realgud 20200722.1113 with GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw scroll bars) of 2019-09-07.

**Comment by CyberShadow** [comment]
A simple but incomplete workaround (doesn't handle sub-keymaps):
```elisp
(defun degudify (map)
  (while (string-prefix-p "realgud" (symbol-name (cdadr map)))
    (setf (cdr map) (cddr map))))
(degudify d-mode-map)
```

**Comment by 813gan** [comment]
Related: #65

**Comment by 813gan** [comment]
If i understand correctly the problem is `realgud-srcbuf-init-or-update` is calling `realgud-populate-common-keys` on map from some non-realgud-related mode. I will take a deeper look soon.

**Comment by rocky** [comment]
Yes. This is a holdover from the days when when this worked on Ruby only. The person who wrote that code, Anders Lindgren, wanted this to work on some very ancient version of GNU Emacs, like version 23 on Windows. So copying rather than use a minor mode was a deliberate choice.
