### ISSUE TITLE
Focus always switching to command buffer short-key mode

### ISSUE THREAD

**Issue by avigan** [realgud/realgud#289]
RealGUD is really awesome, but I am having problems with the short-key mode and the pdb (or ipdb) debugger. Maybe it is the same with other debuggers but python is my primary development language. When I start a debugging session, the cursor is in the source buffer, but as soon as I type any key (e.g. s for stepping), the focus automatically switches to the commande buffer. I have to click again on the source buffer to move the focus back to the source buffer, but again as soon as I type a short-key command it switches back. This makes the short-key mode unusable in practice. 

Any idea what could be causing this and/or how to avoid it?

**Comment by rocky** [comment]
The first thing to check is the information in the debugger info buffer:

```org
#+TITLE: Debugger info for *trepan3k doc.py shell*

This is based on an org-mode buffer. Hit tab to expand/contract sections.

* General Information (realgud-cmdbuf-info)
  - Debugger name       ::	trepan3k
  - Command-line args   ::	["trepan3k","/src/external-vcs/github/mathics/Mathics/mathics/doc/doc.py"]
  - Starting directory  ::	nil
  - Current source-code path  ::	[[/src/external-vcs/github/mathics/Mathics/mathics/doc/doc.py]]
  - Selected window should contain source? :: nil
                                                                        ^^^  true means make sure you stay in source code
  - Last input end      ::	152
  - Source should go into short-key mode? :: t
  - In debugger?        ::	t
  - Ignore file regexps ::	(<string>)
  - remapped file names ::	nil

```

If that's not it, then, I imagine there is a bug in there. How and when GNU Emacs descide to refresh window has changed over the years and different versions, so this may also be version dependent. 

This might be related to #225

**Comment by avigan** [comment]
Sorry for the delay, here is the output of the debugger info buffer:

```
#+TITLE: Debugger info for *pdb test.py shell*

This is based on an org-mode buffer. Hit tab to expand/contract sections.

* General Information (realgud-cmdbuf-info)
  - Debugger name       ::	pdb
  - Command-line args   ::	["python","-m","pdb","/Users/avigan/Desktop/test.py"]
  - Starting directory  ::	nil
  - Current source-code path  ::	[[/Users/avigan/Desktop/test.py]]
  - Selected window should contain source? :: t
  - Last input end      ::	178
  - Source should go into short-key mode? :: t
  - In debugger?        ::	t
  - Ignore file regexps ::	(<string>)
  - remapped file names ::	nil
```

So it does seem that the `Selected window should contain source?` variable is set to `true`.

**Comment by avigan** [comment]
Any idea what could be wrong?

**Comment by rocky** [comment]
No idea. If it hasn't been clear, we are short of people who have time to investigate and fix things.

Open source software is only as good as those who have time time and are willing to investigate and fix problems. 

Hey, maybe you could get involved and narrow this and/or fix it?

**Comment by avigan** [comment]
Sure, I understand. I have been trying to investigate but unfortunately my knowledge of lisp is extremely limited and it is hard for me really start learning that at the moment. I will try though.

**Comment by Sasanidas** [comment]
@avigan I wasn't been able to reproduce the error, can you provide more information?
Like, python version, OS (I'm guessing is MacOS) and maybe the command attach to the n key (or any other key that produce that behaviour). 

As point out in #225 , maybe the issue is in the hook.
Thanks
