### ISSUE TITLE
Command for interrupting executing of debugged process

### ISSUE THREAD

**Issue by nordlow** [realgud/realgud#290]
I'm missing a command in the `*gdb shell*` buffer for interrupting the running process. Useful for tracking down infinite loop bugs. The command should preferably be bound to `C-c C-c`.

Is there a reason why this hasn't already been implemented?

What keybinding should be used in the source buffer?

**Comment by Sasanidas** [comment]
You mean something like the command kill, but bound to a key binding?
If that is the case, it shouldn't be hard to implement (probably).
