### ISSUE TITLE
Error in RealGUD’s autoloads

### ISSUE THREAD

**Issue by nordlow** [realgud/realgud#292]
Recent update triggers error during load as

```
Error in RealGUD’s autoloads: (void-variable +)
```

.

**Comment by rocky** [comment]
Hmm... I looked at this to try to figure out where this is coming from, and can't. This change was given to me by Stefan Monnier though. So I have reverted the last change. 

If this doesn't fix, let me know and  I will revert the one before that which has to do with autoloads (and put back the last change).

**Comment by nordlow** [comment]
The message doesn't stop Emacs from loading though so this is not a show-stopper for me.

**Comment by ShuguangSun** [comment]
There is a leading "+" at line 21 of "realgud-recursive-autoloads.el".

``` elisp
(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "realgud/common/attach" '("realgud:attach-cmdbuf-history")))

+;;;***
```

**Comment by rocky** [comment]
Thanks ShuguangSun!

Should be fixed in 962b5a.

**Comment by nordlow** [comment]
Thanks!
