### ISSUE TITLE
basic usage

### ISSUE THREAD

**Issue by gitrj95** [realgud/realgud#299]
hi, i'm unable to get this up and running with lldb. i have a toy source cpp file i am compiling with clang, and i want to run it through realgud-lldb, add breaks, etc through the command window, but i can't find it

**Comment by jdf-id-au** [comment]
Just for posterity, I had a similarly unclear initial experience with lldb. I think I got it working by:

1. `(use-package realgud-lldb)` (first!; I use [straight](https://github.com/radian-software/straight.el) but assume same with normal use-package)
2. `(use-package realgud)`
3. Open buffer containing C code
4. `M-x lldb`
5. `realgud:attach-cmd-buffer`
6. Enjoy `b` for `realgud:cmd-break` etc
7. `run` in cmd buffer `*lldb projname shell*`

**Comment by rocky** [comment]
@jdf-id-au Thanks for posting this information. 

I have Added it to the wiki: https://github.com/realgud/realgud/wiki/lldb-notes and it is linked to from the [home page](https://github.com/realgud/realgud/wiki)

If you or others have further changes, please feel free to update the wiki. I think or hope it will be more easily visible there. 

Thanks again.
