### ISSUE TITLE
What are the main features that realgud has over gud?

### ISSUE THREAD

**Issue by jgarte** [realgud/realgud#307]
Hi,

What are the main features that realgud has over gud?

If we were to make a feature parity table, what would be missing in gud that realgud has?

**Comment by rocky** [comment]
Please look at https://github.com/realgud/realgud/wiki https://github.com/realgud/realgud/wiki/Debuggers-Available and https://github.com/realgud/realgud/wiki/Features and the narrow your question. 

It doesn't feel like you have made an attempt to seek out any answer first.
