### ISSUE TITLE
debugging within docker container

### ISSUE THREAD

**Issue by fab6** [realgud/realgud#312]
Hi,
is there a way to debug python or cpp programs which are within a docker container?
Maybe this could work using tramp!? 
I tried running the debugger in a container just like this:
![image](https://user-images.githubusercontent.com/3047695/217787829-26a9d702-fae5-408c-8fde-d90e000fe8fa.png)

It does not seem to be the right way...

Would be great if anyone has an advice!
Fab

**Comment by rocky** [comment]
I use the debugger I wrote called [trepan3k](https://python3-trepan.readthedocs.io/en/latest/) . It provides a command called [`set substitute` ](https://python3-trepan.readthedocs.io/en/latest/commands/set/substitute.html) which allows paths from inside the docker container to get mapped to corresponding files on my host computer or laptop. 

For example trepans's [startup profile](https://python3-trepan.readthedocs.io/en/latest/entry-exit.html#startup-profile)  I have: 

```
set substitute /usr/lib64/python36 /home/rocky/.pyenv versions/3.6.15/lib/python3.6
```


In normal operation, when realgud can't find a file mentioned around the debugger prompt, it will prompt you for the name of the file and you can put in the local file name there and relagud remember this docker-to-local filename mapping in `filename-remap-alist`  as a local variable of the command buffer.  Inside the debugger info buffer in outline format, the current list value command buffer's  local variable is shown. 

A couple of other neat things about trepan3k. First there [set autolist](https://python3-trepan.readthedocs.io/en/latest/commands/set/autolist.html) where you an arrange for lines around where you are stopped are show. So if you can't get the automatics file/line tracking you can get context source listing inside the command buffer. 

And finally, when trepan3k can't find the source, for Python versions before 3.9 it has the ability to decompile the bytecode and show the source using that.  (There are no Python decompilers for 3.9+ and that is a completely different topic).  But as last resort, the trepan3k can also show  Python bytecode which when all else fails can give you some idea of where you are; [set autopc](https://python3-trepan.readthedocs.io/en/latest/commands/set/autopc.html) works like "set autolist" for bytecode.

**Comment by fab6** [comment]
Hi,
excuse me for the late response!
Thank you for the info! I will try it out for python. Do you know if there is a way to use it also with c++?
Best Fab

**Comment by rocky** [comment]
Please use https://emacs.stackexchange.com/ or some other venue like this for "how to kinds of questions like this". Thanks.
