### ISSUE TITLE
Not able to see source code in gdb

### ISSUE THREAD

**Issue by aparnapattekar-gh** [realgud/realgud#315]
Issues:
- Not able to see source code with gdb
- Starting directory is nil
- Current source-code path is nil

I invoke debugger as:
M-x realgud:gdb

M-x realgud:cmdbuf-info-describe shows:

This is based on an org-mode buffer. Hit tab to expand/contract sections.

* General Information (realgud-cmdbuf-info)
  - Debugger name       ::	gdb
  - Command-line args   ::	["/auto/sw/gdb","-i=mi","-ex","'add-auto-load-safe-path","/users/ap/project1'","--args","env","/auto/sw/python/bin/pytest","-s","-vvvs","--pdb","--trace","test/python/test1.py"]
  - Starting directory  ::	nil
  - Current source-code path  ::	[[nil]]
  - Selected window should contain source? :: nil
  - Last input end      ::	61250
  - Source should go into short-key mode? :: t
  - In debugger?        ::	t
  - Ignore file regexps ::	nil
  - remapped file names ::	nil

Gdb shell shows:
Current directory: /users/ap/project1/
Command: /auto/sw/gdb -i=mi -ex 'add-auto-load-safe-path /users/ap/project1' --args env /auto/sw/python/bin/pytest -s -vvvs --pdb --trace test/python/test1.py
set annotate 1
set filename-display absolute
=thread-group-added,id="i1"
~"GNU gdb (GDB) 13.1\n"
~"Copyright (C) 2023 Free Software Foundation, Inc.\n"
~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law."
~"\nType \"show copying\" and \"show warranty\" for details.\n"
~"Type \"show configuration\" for configuration details.\n"
~"For bug reporting instructions, please see:\n"
~"<https://www.gnu.org/software/gdb/bugs/>.\n"
~"Find the GDB manual and other documentation resources online at:\n    <"
~"http://www.gnu.org/software/gdb/documentation/>.\n\n"
~"For help, type \"help\".\n"
~"Type \"apropos word\" to search for commands related to \"word\"...\n"
=cmd-param-changed,param="auto-load safe-path",value="/"
~"Reading symbols from env...\n"
~"Reading symbols from .gnu_debugdata for /usr/bin/env...\n"
~"(No debugging symbols found in .gnu_debugdata for /usr/bin/env)\n"
&"Undefined command: \"\".  Try \"help\".\n"
(gdb) 
&"set annotate 1\n"

**Comment by rocky** [comment]
There are a few things I see. 

First, you have `i=mx` and realgud does not support any mx interpreter. 

Second, realgud kicks in only when it sees that you are stopped somewhere the _running_  program. 

When you initially enter gdb, the program you want to debug has not been entered or run yet. Usually, I run `break main` and then `run` to get stopped in a running program. 

Note that `pytest` is a script of some sort, either a Python or sell script. 

In gdb you would break or stop somewhere in the Python interpreter.  When that happens, gdb will report the location of some C  or assembly that it is stopped in. When realgud sees a line of this form, it will parse out the location and show that. 

Finally, the issue tracker is more set up for reporting bugs than how to use kinds of questions. https://emacs.stackexchange.com/ is more suited for this kind of thing. There are more people looking at that than here in the issue tracker.

**Comment by aparnapattekar-gh** [comment]
Thanks Rocky. That worked. I can see the source code when the breakpoint is hit. 
I have one more issue: pytest is a python binary which takes arguments. One of the arguments is --pdb. When this is present, pdb is invoked at the first line in /users/ap/project1. However realgud:pdb is not get invoked. Instead, I get a pdb prompt and again, I am not able to see the source code. Instead, I need to list as follows:
(pdb) list
to see the python source code. Is there a way to also see the python code when a python breakpoint is hit?

**Comment by rocky** [comment]
Post your question on https://emacs.stackexchange.com/  as suggested before and let's see if someone else can answer. If there is no answer in a while, let me know and I'll answer there when I get a chance. 

At some point in the future I will make it more explicit that opening issues is for bugs not "how do I use realgud".
