### ISSUE TITLE
Successfully installed and used realgud, but every time I open Emacs, it gives a warning: "file is missing."

### ISSUE THREAD

**Issue by ententent** [realgud/realgud#317]
First of all, I would like to thank the author for their amazing work on this package.

I have successfully installed realgud and used it for Python program debugging. 

Environment:
OS: macOS 13.3 22E252 x86_64
Emacs: 30.0.50
```elisp
(use-package realgud
  :ensure t
  :demand t)
```

Although it is functional, I encounter a warning message every time I open Emacs.

![image](https://github.com/realgud/realgud/assets/119666897/6812cc5d-bb88-46f2-aef9-a93d41ed08e6)

**Comment by rocky** [comment]
This seems like some sort of installation problem and/or use-package problem and/or problem with GNU Emacs 30 which is not a release yet 29.1 is what is last listed in https://www.gnu.org/savannah-checkouts/gnu/emacs/emacs.html#Releases

You are likely go find more people who have time to help you if you ask on https://emacs.stackexchange.com/ or some other similar Emacs help forum.

**Comment by ententent** [comment]
Thanks, I reinstall emacs with the formula

```
brew tap railwaycat/emacsmacport
brew install emacs-mac --with-module
```

Now, the emacs version is 29.1, and the warning no longer exists.
