### ISSUE TITLE
Support Haskell's ghci debugger

### ISSUE THREAD

**Issue by monsanto** [realgud/realgud#7]
Here are the commands: http://www.haskell.org/ghc/docs/7.4.1/html/users_guide/ghci-debugger.html

**Comment by Pitometsu** [comment]
So is it implemented already? [Here](https://downloads.haskell.org/~ghc/8.0.2/docs/html/users_guide/ghci.html#the-ghci-debugger) new documentation for latest `8.0.2` _GHCi_ version.

**Comment by rocky** [comment]
https://github.com/realgud/realgud/wiki/Debuggers-Supported says no. But maybe you could add this useful debugger. See https://github.com/realgud/realgud/wiki/How-to-add-a-new-debugger
