### ISSUE TITLE
The `realgud:loc-follow` function doesn't exist?

### ISSUE THREAD

**Issue by cpitclaudel** [realgud/realgud#91]
`realgud:loc-follow` is called from a bunch of places, but it doesn't seem to be defined anywhere :/ Did I miss something?

**Comment by rocky** [comment]
Searching history there used to be a function in `loc.el`

```commit 2eb637e7e76007eb93f93c24c05923eccebde7ba
Author: rocky <rocky@gnu.org>
Date:   Sun Jan 18 22:23:57 2015 -0500

    loc.el: Resolve problem where displayed window was not updating goto-char location.
    window.el: simplify logic using loc code.
    test-*: reduce more warnings
```
I guess code that uses realgud:loc-follow should be removed.

**Comment by cpitclaudel** [comment]
Was there? I can see that that commit introduces uses of that function, but it doesn't seem to define the function itself, does it?

**Comment by rocky** [comment]
```
$ git checkout 2eb637e7
```

And then on line 45 I see
```lisp
(defun realgud:loc-follow(mark)
  (when (markerp mark)
    (let ((buffer (marker-buffer mark)))
      (set-buffer buffer)
      (set-window-point (display-buffer buffer) mark)
      (goto-char mark)
    )))
```

**Comment by cpitclaudel** [comment]
Neat, thanks! Somehow I missed it.

Curiosity question: how did you find that function? I tried git-grepping, but I didn't find it :/ I'd be happy to learn :)

**Comment by rocky** [comment]
vc-annotate in fringe which uses that gave me the sha1.

**Comment by cpitclaudel** [comment]
Thanks :)

**Comment by cpitclaudel** [comment]
Fixed :)
